### PR TITLE
Problems: GSSAPI builds broken with picky compilers, Debian/RPM packages do not use GSSAPI, no CI jobs that test GSSAPI

### PR DESCRIPTION
**Pull request by bluca**
Solutions: see commits

### CODE REVIEW

**Comment by bluca** [comment]
@sigiesec when you have time, please have a look at the GSSAPI mechanism changes, I think they match but you never know.
Also a while ago you asked for CI jobs to test GSSAPI, I've added it to a couple of runs (PGM also) where it does not impact the runtime as it was already installing packages.

**Comment by c-rack** [comment]
@bluca so is this ready for merge or shall I wait for feedback from @sigiesec ?

**Comment by bluca** [comment]
@c-rack it is ready, as it builds and runs as far as I can tell. If I botched anything we can revise :-)

**Comment by c-rack** [comment]
👍

**Comment by bluca** [comment]
Thanks!

**Comment by sigiesec** [comment]
@bluca Your changes look good :)

Great that we now have GSSAPI and PGM builds in the CI, this allows making changes with more confidence :)

**Comment by bluca** [comment]
Are you developing on Linux? If so you can install the packages and have the code build on your machine too

**Comment by sigiesec** [comment]
No, unfortunately I am developing under Windows.

**Comment by bluca** [comment]
Ok. PGM should work, at the very least CMake has support for building with it under Windows, gut GSSAPI is autotools-only at the moment I'm afraid.

**Pull request merged**
