### PR TITLE
cmake: Streamline integration allowing config of CMAKE_*_OUTPUT_DIRECTORY

### PR DESCRIPTION
**Pull request by jcfr**
Setting EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH variables is deprecated

### CODE REVIEW

**Comment by jcfr** [comment]
@lassoan I added your commit on top of this topic :+1:

**Comment by bluca** [comment]
Everything else that's required should already be there

**Comment by jcfr** [comment]
>> I think the new file needs to be added to EXTRA_DIST of Makefile.am
> Everything else that's required should already be there

Locally running the following allow to generate the source distribution `zeromq-4.3.1.tar.gz` and confirm it includes all CMake modules

```
./autogen.sh 
./configure 
make dist
```

Is there anything else needed to move forward with this topic ?

**Comment by jcfr** [comment]
Thanks @bluca

**Comment by bluca** [comment]
@jcfr could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by jcfr** [comment]
Thanks for reminder, as soon as I hear back from our compliance team I will finalize the PR.

**Pull request merged**
