### PR TITLE
Problem: need to collect grants to relicense under MPLv2

### PR DESCRIPTION
**Pull request by hintjens**
Solution: kick off process with grant from iMatix

### CODE REVIEW

**Comment by hintjens** [comment]
Please don't merge yet, this needs review (exceptionally :)

**Comment by c-rack** [comment]
ok :-)

**Comment by hitstergtd** [comment]
@hintjens,
Would this not also require a rationale for folks to know why the license change has to happen or is that already elucidated or exemplified elsewhere with regard to ZeroMQ?

+1 btw.

**Comment by abligh** [comment]
From a legal point of view under the circumstances users of ZMQ would probably be safest if a legal entity which was going to continue in existence held the copyright (as opposed to them relying on a prior grant from an entity that no longer exists). Once this task is completed, have you considered an assignment to (e.g.) the Linux Foundation or the FSF?

**Comment by hitstergtd** [comment]
Or create our own Foundation instead of going with FSF and/or the Linux Foundation; so that we can protect the ZMQ way of doing things.

Although this discussion has the potential to enter bikeshed territory so probably best to keep it as a distinctly separate conversation from the relicensing effort.

**Comment by hintjens** [comment]
FWIW I'm opposed to foundation creation because it inevitably ends up in
bike shedding committee design. It is a hassle that costs more than it's
worth *unless* there is a real financial interest, e.g. a place to hold
large donations from firms.

Please let's not create centralized structures to care for ZeroMQ.

**Comment by ewen-naos-nz** [comment]
This covers most of the [things I asked about](http://lists.zeromq.org/pipermail/zeromq-dev/2016-April/030295.html), but in an ideal world there would be a clearer statement that all the FastMQ copyrights were transferred to iMatix by date X.  The current version says iMatix acquired FastMQ, and then later liquidated FastMQ, which potentially could be read as "iMatix owned FastMQ as a subsidary, FastMQ owned the ZeroMQ copyrights, FastMQ was liquidated while still owning the copyrights" -- in which case "the FastMQ copyrights are in a legal limbo" owned by an entity that no longer exists (which might sound silly, but it happens a lot).  Also, since the document being collected is Markdown, let's add links.

1.  Link to (new) zeromq-dev URL of announcement of iMatix acquiring ZeroMQ (http://lists.zeromq.org/pipermail/zeromq-dev/2009-November/001353.html and/or http://imatix.wikidot.com/press:fastmq-acquisition).

2.  Add an explicit statement after "The FastMQ legal entity was subsequently liquidated." that says, eg "and the FastMQ copyrights were transferred to iMatix Corporation sprl at this time".   Or if they were transferred before FastMQ liquidation, add a sentence "The FastMQ copyrights in ZeroMQ were transferred to iMatix Corporation sprl ...", eg "as part of this purchase".)  Possible examples below.

3.  Link to github commit updating the copyright notice (https://github.com/zeromq/libzmq/commit/4f6baf4dde627656b63cc4e2acdb78a8577ba640), which is 2010-01-05.  Was that the date of copyright transfer?  Or were they transferred previously?  Some explicit statement that the copyrights were transferred by that date would potentially help in future.

Without public access to the contract/documents that effected the acquisition/transfer there will be no way for anyone to investigate this later.  Which is why I'm being pedantic about having it explicitly stated now while we can, to try to head off any future arguments.

Eg (please edit to reflect what happened):

    2. On 2009-11-01, iMatix exercised an option to acquire FastMQ and its assets, 
    including ZeroMQ.  On or before 2010-01-05 the FastMQ copyrights in ZeroMQ were 
    transferred to iMatix ([commit](https://github.com/zeromq/libzmq/commit/4f6baf4dde627656b63cc4e2acdb78a8577ba640)) .
    The FastMQ legal entity was subsequently liquidated.

Or:

    2. On 2009-11-01, iMatix exercised an option to acquire FastMQ and its assets, 
    including ZeroMQ.  The FastMQ legal entity was subsequently liquidated and
    all its copyrights were transferred to iMatix on or before 2010-01-05 
    ([commit](https://github.com/zeromq/libzmq/commit/4f6baf4dde627656b63cc4e2acdb78a8577ba640)).

Ewen

PS: I agree that a multiplicity of copyright ownership and mutual share-alike licensing is safer for a community project than a copyright assignment structure.  As an example of what happens with the alternatives consider, eg, MySQL (now owned by Oracle).

**Comment by ewen-naos-nz** [comment]
Separately, it might make sense to consider assigning the *iMatix* copyrights to a legal entity that will continue in existence (but not trying to have that entity collect up other copyrights in the code).  Otherwise I expect that the iMatix copyrights will become one of those "entity disappeared owning the copyright" situations.  Leaving LGPL/MPLv2 licensed usage as the only possible options *ever*.  Perhaps the iMatix copyrights could, eg, be transferred to the new BDFL?  Or some other trusted entity/individual whose only role is, eg, to decide on future copyright relicensing.  Or perhaps it really is best that LGPL/MPLv2 become the only options *ever*.

Ewen

**Comment by ewen-naos-nz** [comment]
One final comment on the *form* of the solution.  Perhaps it should be a *directory* with a README.md explaining why and one-file-per-entity granting permission?  That way it will be easier to verify that only trusted github accounts/developers/etc changed the text relating to a given entity.

Ewen

**Comment by hintjens** [comment]
I think we'll be fine with LPGLv3+ / MPLv2 as the only license options ever for libzmq. We're going to be lucky to succeed in relicensing to MPLv2 as it is. Let's not over-think this one. Feel free to reorganize the file structures... 

(The usual way to achieve arbitrary relicensing in the future is to grant under BSD/MIT but I do not want that, it's MPLv2 or the current LGPLv3+static link exception).

**Comment by ewen-naos-nz** [comment]
Since (a) I don't know any way to edit someone else's pull request and (b) this still isn't merged, I have started again.  See pull requests for [RELICENSE/README.md](https://github.com/zeromq/libzmq/pull/1924) and [RELICENSE/naos_ltd.md](https://github.com/zeromq/libzmq/pull/1925) (the latter is based on the former, but changes only a new file so could be cherry picked).

If this seems a reasonable approach then I'd suggest merging https://github.com/zeromq/libzmq/pull/1924, then changing this pull request to create RELICENSE/imatix.md (or similar), perhaps without the initial paragraph, and merging that.  Then perhaps followed by https://github.com/zeromq/libzmq/pull/1925 (which shouldn't conflict, due to creating a new file).

Ewen

**Comment by ewen-naos-nz** [comment]
Also, the README.md and/or RELICENSE.md should probably link to:

http://zeromq.org/area:licensing

which talks about the rational for MPLv2 relicensing; I've just updated pull request #1924 to link to that as well, but if merging this pull request is chosen it'd be useful to update it to include such a link.

Ewn

**Comment by bluca** [comment]
@ewen-naos-nz @hintjens - couple of questions:

1) Is this process gathering the permission only from corporate copyright holders, or from individuals as well?
2) Is the plan to dual-license LGPL3 + MPL2, or to remove the LGPL3 and use only MPL2?

**Comment by hintjens** [comment]
* it must be from individual and corporate copyright holders
* we'd switch over to MPLv2 as we've done in other projects
* I honestly think the time & cost of collecting these grants is
prohibitive without a sponsor

**Comment by hitstergtd** [comment]
@hintjens - followup to your question - 
What do you mean by "sponsor" in this context? Is it that someone needs to individually contact anyone with attributable claim under the present license?

**Comment by hintjens** [comment]
Sponsor as in someone to pay for the (IMO considerable) effort it will take.

**Comment by ewen-naos-nz** [comment]
To effectively re-license a project you'd need to get agreement (in "writing") from substantially all copyright holders in the code, that covers substantially all the copyright in the code (eg, well over 90% of the copyright holders and well over 90% of the code).  So that would cover both individuals who own copyright in the code, and also companies that own copyright in the code -- and in the cases where it is unclear whether the individual or the company owns the code, probably we would want a license grant or "quitclaim" ("I declare I do not own this or have any claim to it") from both the individual and company.

As Pieter says, it's potentially pretty time consuming as you have to identify and track down all the copyright and potential copyright holders, and chase them up to send something in writing.  (The first 50-80% of the contributors/code is probably easy, but the last 20% will be hard; and the license can't be changed without getting most of that "last 20%" and/or "clean room" replacing the code you can't get relicensed.)

My guess is several days of work, spread over many months of chasing people.  (And with companies that may own copyright, potentially talking the lawyers of said companies through agreeing to send something in writing, even if it is just a quitclaim.)

Ewen

**Comment by sunkin351** [comment]
Don't you just love copyright? XD

**Comment by hintjens** [comment]
Well, the original intention was to make it _hard_ to capture ZeroMQ and
relicense it by force. We've succeeded in that.

**Comment by sunkin351** [comment]
Indeed. What I would suggest, you don't have to do this, but just in case you have to do something like this again, is ask everyone who makes a good sized contribution to add themselves to the authors file, or maybe a new "CONTRIBUTORS" file (If there isn't already a contributors file). (And maybe add the company they represent or if they are just an individual just leave their name). Just a thought.

**Pull request merged**
