### PR TITLE
Revert "problem:Socket try to access closed mutex"

### PR DESCRIPTION
**Pull request by somdoron**
Reverts zeromq/libzmq#1975

problem: patch is no good

### CODE REVIEW

**Comment by bluca** [comment]
Thanks! Your revert branch was pushed to the zeromq/ repo rather than your fork, I assume that was a finger slip?

**Comment by somdoron** [comment]
Yes, I guess its the default... Deleting it

**Comment by somdoron** [comment]
Done, I used the github ui to fo the revert, not pushed from machine. There
is an option to create the branch on different repository?

**Comment by bluca** [comment]
Thanks! Good question, I don't use the Github UI so I'm afraid I don't know, sorry.

**Pull request merged**
