### PR TITLE
Problem: insufficient unit tests for poller concept and ypipe

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: add some unit tests, fix resulting test failures, add documentation on poller concept

Resolve several minor issues including formatting, test timeouts, test output, ...

### CODE REVIEW

**Comment by bluca** [comment]
@sigiesec some tests are failing when building in some distros:

```
[  225s] FAIL: unittests/unittest_poller
[  225s] ===============================
[  225s] 
[  225s] Bad file descriptor (src/epoll.cpp:103)
[  225s] unittests/unittest_poller.cpp:211:test_create:PASS
[  225s] #0  0x55e12448fac9 in ./unittests/unittest_poller (zmq::zmq_abort(char const*)+0x9)
[  225s] #1  0x55e12448f54d in ./unittests/unittest_poller (zmq::epoll_t::rm_fd(void*)+0x11d)
[  225s] #2  0x55e124483a26 in ./unittests/unittest_poller (test_events_t::in_event()+0x16)
[  225s] #3  0x55e12448eabe in ./unittests/unittest_poller (zmq::epoll_t::loop()+0x12e)
[  225s] #4  0x55e1244a8b12 in ./unittests/unittest_poller (thread_routine+0x52)
[  225s] #5  0x7f25855a96da in /lib/x86_64-linux-gnu/libpthread.so.0 (start_thread+0xca)
[  225s] #6  0x7f2584a4e1b8 in /lib/x86_64-linux-gnu/libc.so.6 (clone+0x5f)
[  225s] #7  0x5f in ? (+0x5f)
[  225s] 
[  225s] FAIL unittests/unittest_poller (exit status: 134)
```

https://build.opensuse.org/package/live_build_log/network:messaging:zeromq:git-stable/libzmq/xUbuntu_17.04/x86_64

**Comment by sigiesec** [comment]
Regarding formatting: there appears to be some instability in indenting comments around preprocessor directives :( We can apply the suggested fixes, but I have the impression that some changes in the rest of the file will cause them to go back.

**Comment by sigiesec** [comment]
Regarding the failing unit test: I was able to reproduce it once, and got:
```
Bad file descriptor (src/epoll.cpp:103)
```

I will try to reproduce it while debugging.

**Comment by sigiesec** [comment]
It seems that the fd created by make_fdpair in test_add_fd_and_remove_by_timer is closed at the time.

**Pull request merged**
