### PR TITLE
[WiP] Problem: after disconnecting an inproc router socket, attempting to r…

### PR DESCRIPTION
**Pull request by sigiesec**
…eceive a multipart message causes an assertion in fq.cpp (see #3485)

Solution: allow receiving messages in state term_req_sent1

### CODE REVIEW

**Comment by sigiesec** [comment]
@cenzhao I was able to fix the issue you describe in #3485, however the change causes the existing test in test_disconnect_inproc to fail. Actually my assumption in #3485 was not correct. While the pipe is terminated asynchronously as I wrote, the assertion failure you saw is caused by the state change that is done synchronously within zmq_disconnect. I wasn't aware of that you are using inproc sockets here, which behave somewhat differently from sockets that use a "real" transport.

@bluca I am not sure if the expectation of that test is valid. After my change, now a message is received that is not expected to be received.

**Comment by bluca** [comment]
I think the test expected the disconnect to be synchronous, at least in terms of stopping receives - it might be fine to change it, but I can't tell off the top of my head of what the full implications would be

**Comment by cenzhao** [comment]
thanks @sigiesec for addressing this issue, I used "inproc" for easily demonstrate the problem. In our Facebook production, we saw the issue over "tcp" socket. Does your fix also address "tcp" case?

after `disconnect()`, I expect either 1. receive the whole message (3 parts) or 2. receives nothing (poll() on that socket will block). I think 2. would be ideal case :)

**Comment by sigiesec** [comment]
@cenzhao ok. I don't think my fix fixes the tcp case. I will give that another look

**Comment by sigiesec** [comment]
I am sorry, but I did not find time yet to give the tcp case a look, and I fear I also won't be able to do this in the near future. I would therefore close this pull request for now, since it doesn't build correctly in its current state.

**Comment by bluca** [comment]
This is getting stale and not progressing, so I'll close it for now.

**Pull request closed without merging**
