### PR TITLE
Fix redirecting location of pdb via CMAKE_PDB_OUTPUT_DIRECTORY.

### PR DESCRIPTION
**Pull request by Kentzo**

### CODE REVIEW

**Comment by c-rack** [comment]
Thanks!

Now, for backporting this to 4-1, could you please open an issue (you can directly close it with pointer to your just merged pull request), so that we have something to refer to in the 4-1 news?

**Comment by Kentzo** [comment]
@c-rack Where should I open the issue?

**Comment by c-rack** [comment]
@Kentzo In libzmq project please:
https://github.com/zeromq/libzmq/issues

**Comment by c-rack** [comment]
See also the NEWS file in zeromq4-1, where we reference the libzmq issues:
https://github.com/zeromq/zeromq4-1/blob/master/NEWS

**Comment by Kentzo** [comment]
@c-rack Ok. But Isn't issue number created automatically for each PR. E.g. #1672 in this case.

**Comment by Kentzo** [comment]
https://github.com/zeromq/libzmq/issues/1673

**Comment by hintjens** [comment]
Actually, I'm fine using the PR number as issue number.

**Comment by Kentzo** [comment]
@hintjens Would be cool if you can backport it today :)

**Comment by c-rack** [comment]
Ok, learned that :-)
Seems you have already clarified this in ﻿http://zeromq.org/intro:ask-for-help as well...

**Comment by Kentzo** [comment]
I've seen you're preparing to release 4.1.5 I'm debugging one issue compiling zeromq after https://github.com/GreatFruitOmsk/zeromq4-1/commit/849e5b07d982e7c0917a13d9ff22d447817dd7fe on Windows.

**Pull request merged**
