### PR TITLE
problem: no way to send raw udp messages with zeromq

### PR DESCRIPTION
**Pull request by somdoron**
@bluca I think this is the issue, however I'm not sure...

### CODE REVIEW

**Comment by bluca** [comment]
Let's wait for the run to finish to confirm

**Comment by bluca** [comment]
@somdoron - nope, still fails :-(
After lunch I'll run locally - in theory it should have more info in the backtrace (line number and so on), not sure why it's not doing that on Travis

**Comment by somdoron** [comment]
I think i found it...

**Comment by somdoron** [comment]
I think it is fixed now, waiting for build

**Comment by somdoron** [comment]
memrchr is not supported on windows :-(

**Comment by bluca** [comment]
Now there's a leak:

https://travis-ci.org/zeromq/libzmq/jobs/130553362

**Comment by somdoron** [comment]
@bluca everything should be fine now, waiting for build to confirm

**Comment by bluca** [comment]
All good, great stuff, thanks for fixing!

**Pull request merged**
