### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by sigiesec**

### CODE REVIEW

**Comment by bluca** [comment]
There's a segfault under valgring which seems reproducible:

==19297== Process terminating with default action of signal 11 (SIGSEGV)
==19297==  Access not within mapped region at address 0x59
==19297==    at 0x4E8CFBE: zmq::pipe_t::check_write() (pipe.cpp:222)
==19297==    by 0x4E8D037: zmq::pipe_t::write(zmq::msg_t*) (pipe.cpp:237)
==19297==    by 0x4E6E8F1: zmq::dist_t::write(zmq::pipe_t*, zmq::msg_t*) (dist.cpp:214)
==19297==    by 0x4E6E692: zmq::dist_t::distribute(zmq::msg_t*) (dist.cpp:175)
==19297==    by 0x4E6E4EE: zmq::dist_t::send_to_matching(zmq::msg_t*) (dist.cpp:151)
==19297==    by 0x4ECF09B: zmq::xpub_t::xsend(zmq::msg_t*) (xpub.cpp:317)
==19297==    by 0x4EAEFC2: zmq::socket_base_t::send(zmq::msg_t*, int) (socket_base.cpp:1184)
==19297==    by 0x4ED737B: s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int) (zmq.cpp:361)
==19297==    by 0x4ED81E8: zmq_msg_send (zmq.cpp:615)
==19297==    by 0x401946: test_disconnect_inproc() (test_disconnect_inproc.cpp:113)
==19297==    by 0x40543D: UnityDefaultTestRun (unity.c:1339)
==19297==    by 0x401ABD: main (test_disconnect_inproc.cpp:134)

**Comment by sigiesec** [comment]
Fixed that. I was mislead by a comment, which seems to be wrong to me. I tried to improve that as well.

**Comment by bluca** [comment]
Thanks - formatting is not happy now

**Comment by sigiesec** [comment]
Hopefully fixed formatting now.

**Pull request merged**
