### PR TITLE
Add semicolon to ZMQ_NON_COPYABLE_NOR_MOVABLE macro

### PR DESCRIPTION
**Pull request by javabudd**
Adds a missing semicolon that breaks building on windows/msys2

### CODE REVIEW

**Comment by sigiesec** [comment]
Unfortunately, this breaks some gcc builds:
```
../../src/thread.hpp:132:44: error: extra ‘;’ [-Werror=pedantic]

ZMQ_NON_COPYABLE_NOR_MOVABLE (thread_t);

```
I guess this should rather be changed in the definition of the macro.

**Comment by bluca** [comment]
Also relicense statement is missing

**Comment by javabudd** [comment]
@bluca I'm not sure what to do about the relicense statement, any tips?

**Comment by bluca** [comment]
See https://github.com/zeromq/libzmq/blob/master/RELICENSE/README.md

**Comment by bluca** [comment]
One of the windows builds fails:

101>c:\projects\libzmq\src\atomic_ptr.hpp(235) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
101>c:\projects\libzmq\src\atomic_ptr.hpp(235) : warning C4183: 'static_assert': missing return type; assumed to be a member function returning 'int'
101>C:\projects\libzmq\src\ypipe.hpp(201) : error C2059: syntax error : 'constant'
101>C:\projects\libzmq\src\ypipe.hpp(201) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
101>C:\projects\libzmq\src\ypipe.hpp(201) : warning C4183: 'static_assert': missing return type; assumed to be a member function returning 'int'

**Comment by javabudd** [comment]
I'm not entirely sure if adding the semicolon to the macro is the best approach, this PRE has some valid arguments against it.

https://wiki.sei.cmu.edu/confluence/display/c/PRE11-C.+Do+not+conclude+macro+definitions+with+a+semicolon

**Comment by bluca** [comment]
Any update on this?

**Comment by javabudd** [comment]
@bluca I can not figure out why this is not working on msvc9 builds, any ideas?

**Pull request closed without merging**
