### PR TITLE
fixed zmq assertion in signaler.cpp under ubuntu

### LINKED ISSUE #1583: zmq assertion in signaler.cpp:292
After updating to the recent version i've began to get this error (the program was run under valgrind, ubuntu 14.04):

> Resource temporarily unavailable (/home/ymax/Projects/tester/zeromq-latest/src/signaler.cpp:292)
> ==14071==    by 0x74B4CC8: raise (raise.c:56)
> ==14071==    by 0x74B80D7: abort (abort.c:89)
> ==14071==    by 0x641801: zmq::zmq_abort(char const*) (err.cpp:84)
> ==14071==    by 0x65029C: zmq::signaler_t::recv() (signaler.cpp:292)
> ==14071==    by 0x642198: zmq::mailbox_t::recv(zmq::command_t*, int) (mailbox.cpp:87)
> ==14071==    by 0x654F99: zmq::socket_base_t::process_commands(int, bool) (socket_base.cpp:1256)
> ==14071==    by 0x65443C: zmq::socket_base_t::send(zmq::msg_t*, int) (socket_base.cpp:985)
> ==14071==    by 0x633763: s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int) (zmq.cpp:348)
> ==14071==    by 0x633898: zmq_send (zmq.cpp:373)
> ...

Looking into sources I've found the possible cause:
the assertion happens here:
```c
void zmq::signaler_t::recv ()
{
    //  Attempt to read a signal.
#if defined ZMQ_HAVE_EVENTFD
    uint64_t dummy;
    ssize_t sz = read (r, &dummy, sizeof (dummy));
    errno_assert (sz == sizeof (dummy));
```
And the creation point of socket is:
```c
zmq::signaler_t::signaler_t ()
{
    //  Create the socketpair for signaling.
    if (make_fdpair (&r, &w) == 0) {
        unblock_socket (w);
        unblock_socket (r);
    }
```
Here we intentionally put socket into non-blocking state. And in this case read can return -1. From man of eventfd: 
> If the eventfd counter is zero at the time of the call to read(2) then the call either blocks... or fails with the error EAGAIN if the file descriptor has been made nonblocking.

### PR DESCRIPTION
**Pull request by ymax**
Fixes #1583

### CODE REVIEW

**Comment by c-rack** [comment]
Thanks!

**Comment by pijyoi** [comment]
I think an issue is the semantics for code calling this recv() method is that a signal got received upon return.

So if we return on EAGAIN, this contract is broken. 

The issue triggering this assertion may be elsewhere. The assertion is telling us that our assumptions are wrong.

**Comment by ymax** [comment]
pijyoi, you are right. on the other hand as we have wait() and recv() as public methods it is supposed that we can call recv() without wait() and in that case (and taking into account the non-blocking mode of the socket)  it is normal to receive EAGAIN. 
IMHO the best solution may be to add wait() into recv() if the EAGAIN must not happen, or create a method wait_recv(timeout) (and move wait(), recv() to private) so the result will be predictable and wait timeout (EAGAIN) will be expected.

**Comment by pijyoi** [comment]
There are only 3 places in the source that call signaler::recv()
1) mailbox.cpp
2) socket_base.cpp
3) zmq.cpp
The last two cases being for thread_safe sockets only, which are a recent addition.

For the first case, a *successful* call to signaler::wait() is made prior to calling signaler::recv(). So if signaler::recv() fails, that might indicate that there is a race somewhere?

See also #1554, which highlights an issue in signaler::wait()

**Comment by pijyoi** [comment]
@ymax, I have made pull request #1595 that reverts signaler::recv() to its old state and created signaler::recv_failable() that allows EAGAIN and also returns an error code to the caller.

I have only made mailbox.cpp use this new method.

@will133, this pull request also allows the WSAEWOULDBLOCK in the Windows codepath.

**Pull request merged**
