### PR TITLE
Problem: style broken in src/windows.hpp

### PR DESCRIPTION
**Pull request by hitstergtd**
**Solution:**
Wrap to lte 80 chars and fix it.

### CODE REVIEW

**Comment by hitstergtd** [comment]
I will merge and close the PR myself. Since its been sitting for a while now.

**Comment by bluca** [comment]
@hitstergtd - was away :-) I don't think this was merged? I don't see the commits in the tree. If you want to reopen it, I'll merge it.

**Comment by hitstergtd** [comment]
Ha ha. No worries. Ok I will reopen the pull.

**Comment by hitstergtd** [comment]
Thanks!

**Pull request merged**
