### PR TITLE
REPLACE CMAKE MSVC VERSION SUFFIX VARIABLE

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
Replace _zmq_COMPILER with CMAKE_VS_PLATFORM_TOOLSET. This will solve #1393 and add suffix generation support for every MSVC compiler supported by CMAKE.

### CODE REVIEW

**Comment by hintjens** [comment]
Thanks.

**Comment by snikulov** [comment]
@hintjens Can this be merged to zeromq4-1 repo?

**Comment by hintjens** [comment]
The patch causes conflicts on 4-1; if you'd like to resolve these and send a pull request straight to zeromq4-1 then I'll merge it. I'd do it but can't test the results.

**Comment by snikulov** [comment]
@hintjens done with https://github.com/zeromq/zeromq4-1/pull/73

**Comment by hintjens** [comment]
Great, thanks!

**Pull request merged**
