### PR TITLE
Problem: build broken with Sun Studio, tests fail on debian/kfreebsd and debian/hurd, DRAFT zmq_poll is slow

### PR DESCRIPTION
**Pull request by bluca**
Solutions: fix them

### CODE REVIEW

**Comment by sigiesec** [comment]
What exactly is the problem with 6d7aeb056f11e6fd2429fa90bc175da0922d306b and Sun Studio?

**Comment by bluca** [comment]
I mentioned it here https://github.com/zeromq/libzmq/pull/3220

```
gmake[1]: Entering directory `/tmp/zeromq-4.3.0'
  CXX      src/src_libzmq_la-session_base.lo
"src/stream_engine.hpp", line 245: Warning: zmq::stream_engine_t::plug hides the function zmq::io_object_t::plug(zmq::io_thread_t*).
"src/udp_engine.hpp", line 69: Warning: zmq::udp_engine_t::plug hides the function zmq::io_object_t::plug(zmq::io_thread_t*).
"src/session_base.cpp", line 555: Error: Cannot use std::pair<char[4], zmq::own_t*(zmq::session_base_t::*)(zmq::io_thread_t*,bool)> to initialize std::pair<std::string, zmq::own_t*(zmq::session_base_t::*)(zmq::io_thread_t*,bool)>.
"src/session_base.cpp", line 576: Error: The type "std::pair<std::string, zmq::own_t*(zmq::session_base_t::*)(zmq::io_thread_t*,bool)>[]" is incomplete.
"src/session_base.cpp", line 580: Error: Cannot use std::pair<char[4], void(zmq::session_base_t::*)(zmq::io_thread_t*)> to initialize std::pair<std::string, void(zmq::session_base_t::*)(zmq::io_thread_t*)>.
"src/session_base.cpp", line 595: Error: The type "std::pair<std::string, void(zmq::session_base_t::*)(zmq::io_thread_t*)>[]" is incomplete.
```

Unfortunately a simple change like the following generates yet more errors, as the compiler fails to find a match for the method:

```
-std::make_pair (protocol_name::tcp,
-std::make_pair (std::string(protocol_name::tcp),
```

**Comment by bluca** [comment]
I think in general Sun Studio just refuses to automatically convert char * to std::string like other compilers do, we hit that before

**Comment by sigiesec** [comment]
Ah, sorry, I didn't see your other comment. I somehow lost track due to the high activity of the last days (which is a good thing :) ). I will try to give this a look, and see that the changes can be applied again without breaking Sun Studio. I also remember that we had a similar issue before.

**Comment by bluca** [comment]
Yes we did, it was similar with std::string:

https://github.com/zeromq/libzmq/pull/3092
https://github.com/zeromq/libzmq/pull/3095

**Pull request merged**
