### PR TITLE
Cleanup socket FD after pair is established. Fix #4086

### LINKED ISSUE #4086: ZeroMQ 4.3.3 Unix Sockets Fill Temp Folder, Prevent Login (Windows)
# Issue description

The temp directory, `%LOCALAPPDATA%\Temp`, is rapidly filled with folders containing a single "socket" file. These files are not deleted even after the ZeroMQ context is closed, causing the temp folder to fill. We believe that these are IPC sockets used for ZMQ internal communication.

Running for a long period of time (>30 minutes or so) produces so many files in the temp folder that after logging out or restarting the computer, the user will no longer be able to log in until the Temp folder has been cleared. (Windows hangs at the "Welcome" screen.) This issue knocked out 5+ development machines before it was discovered.

@sigiesec may be able to shed more light on this issue, since he appears to have worked the initial Unix sockets support for Windows.

# Environment

* libzmq version (commit hash if unreleased): 4.3.3
* OS: Windows 10 (various builds but confirmed on v1909)

# Minimal test code / Steps to reproduce the issue

1.  Create a ZMQ context in thread A, with a UDP DISH socket receiving in thread B and a UDP RADIO socket transmitting in thread C.
2. Monitor `%LOCALAPPDATA%\Temp` folder usage for appearance of hexadecimal-named folders containing a "socket" file.
3. Stop program before computer is nuked.

### PR DESCRIPTION
**Pull request by zedalaye**
Avoid filling Temp directory with temporary files.

### CODE REVIEW

**Comment by zedalaye** [comment]
Need comment. Do you think this fix would do the job ?

**Comment by bluca** [comment]
Have you tested this? I have no idea how it works on Windows, but on other platforms removing the socket file breaks things when it's in use

**Comment by bluca** [comment]
Also please add a commit with a relicense statement as indicated in https://github.com/zeromq/libzmq/tree/master/RELICENSE

**Comment by zedalaye** [comment]
@bluca at this point the listener socket is closed, so removing the file should not be a problem, should it?

**Comment by bluca** [comment]
I'm really not sure, I have no idea how the Windows AF_UNIX implementation works. Have you tested this and confirmed it works?

**Comment by bluca** [comment]
Please rebase and squashfs the first and second commits, and force push

**Comment by zedalaye** [comment]
> I'm really not sure, I have no idea how the Windows AF_UNIX implementation works. Have you tested this and confirmed it works?

My app behaves exactly the same. The only difference is that my Temp directory is not bloated with xxxx.xx\socket files.

I tracked the call to make_fdpair() down to ZMQ creating signaling sockets. How can I test if I broke somehing ?

**Comment by bluca** [comment]
clang formatter is not happy, please fixup:

```
--- a/src/ip.cpp
+++ b/src/ip.cpp
@@ -626,7 +626,7 @@ int zmq::make_fdpair (fd_t *r_, fd_t *w_)
     if (!filename.empty ()) {
         rc = ::unlink (filename.c_str ());
         if ((rc == 0) && !dirname.empty ()) {
-            rc = ::rmdir(dirname.c_str ());
+            rc = ::rmdir (dirname.c_str ());
             dirname.clear ();
         }
         filename.clear ();
@@ -649,7 +649,7 @@ error_closelistener:
     if (!filename.empty ()) {
         rc = ::unlink (filename.c_str ());
         if ((rc == 0) && !dirname.empty ()) {
-            rc = ::rmdir(dirname.c_str ());
+            rc = ::rmdir (dirname.c_str ());
             dirname.clear ();
         }
         filename.clear ();
```

**Comment by zedalaye** [comment]
> clang formatter is not happy, please fixup:

Done. I can't resist the urge to tell you that adding spaces before () is very... weird.

**Comment by bluca** [comment]
> > clang formatter is not happy, please fixup:
> 
> Done. I can't resist the urge to tell you that adding spaces before () is very... weird.

"I don't pretend to understand Brannigan's Law. I merely enforce it." [cit.]

**Pull request merged**
