### PR TITLE
Fixed missing subscriptions on XPUB with manual subscriptions

### PR DESCRIPTION
**Pull request by djelenc**
The patch fixes the issue #1568.

### CODE REVIEW

**Comment by djelenc** [comment]
This is strange, Travis seems to fail tests that pass nicely on my machine...

**Comment by c-rack** [comment]
@djelenc I have checked out your branch and it also passes all tests on my machine.

**Comment by djelenc** [comment]
Interesting. I see that after merge, more test are passing, but still 
not all. What is even stranger is that _different_ test fail from one 
build to another...

**Comment by c-rack** [comment]
Confirmed. I restarted the build a couple of times and some tests are flapping. Don't know why.

**Comment by djelenc** [comment]
Is there any way I can run tests on Travis without sending a PR? I need 
some way to debug this...

**Comment by bluca** [comment]
@djelenc - you can enable Travis on your personal fork of this repository, and then every time you push to any branch the CI will run. Just head over to https://travis-ci.org/ and follow the instructions to link your github account. It's all free for open source projects.

**Pull request merged**
