### PR TITLE
Last bits of Hurd support

### PR DESCRIPTION
**Pull request by gcsideal**
Work of Svante Signell, quoting him:
"I did manually issue configure, make and make check in the git directory, and they passed fine. It seems like even the git version, 4.2.0?, should build when packaged."

### CODE REVIEW

**Comment by bluca** [comment]
:+1:

**Comment by hintjens** [comment]
@gcsideal configure.ac:284 says:

    gnu*)

And I'm fairly sure it should say:

    *gnu*)

Can you check? I'm backporting Hurd support into zproject, so we'll have it in CZMQ, Zyre, and so on.

**Comment by gnu-srs** [comment]
No, for $host_os it should be gnu* and for $host *-gnu* as the last option, see
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html. Otherwise other systems ending with gnu* are included too.

**Comment by hintjens** [comment]
Ah, I thought the asterisk was some kind of delimiter. OK, makes sense,
thanks for that.

**Comment by hintjens** [comment]
I've added GNU/Hurd support to CZMQ though cannot test it, if you get the
chance to do so, that'd be cool:
https://github.com/hintjens/czmq/commit/3104ad1a399cf03a9e7f14ad32f3a6c3eacec7d8

**Comment by bluca** [comment]
@gcsideal could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by bluca** [comment]
@gcsideal  another ping. Please consider helping us with the relicense. Thank you!

**Pull request merged**
