### PR TITLE
Problem: term "identity" is confusing

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: replace by "routing id"

### CODE REVIEW

**Comment by sigiesec** [comment]
There is some inconsistency, test_stream is failing. I am working on that, along with changing terminology in all of the tests. Will send another PR soon

**Comment by sigiesec** [comment]
The problem is that ZMTP uses "Identity" as a string as well. Of course we cannot change that before a potential ZMTP 4.0

**Comment by sigiesec** [comment]
See #2745

**Comment by bluca** [comment]
Sorry I'll be without laptop until Monday, I can look next week

**Comment by bluca** [comment]
But I can see from my mobile on OBS that all stable builds are failing in the test_stream and all draft builds are not compiling

**Comment by somdoron** [comment]
@sigiesec I will send a revert PR, so please submit a PR again when the issue is solved.

**Pull request merged**
