### PR TITLE
Add ZMTP connection heartbeats

### PR DESCRIPTION
**Pull request by jbreams**
This commit adds ZMTP connection heartbeats described in
http://rfc.zeromq.org/spec:37/ZMTP.

### CODE REVIEW

**Comment by hintjens** [comment]
@jbreams this is awesome! :)

Could you add a description of the new socket options to doc/zmq_setsockopt.txt?

Usually the timeout can be fixed to 2 or 3 times the interval, so this option could be hidden from the API unless/until we find that we absolutely need to expose it.

**Comment by jbreams** [comment]
Sure, will do. I also see there's a compile failure in VS2013 in the test I wrote for heartbeats, so I'll fix that as well.

**Comment by jemc** [comment]
Cool!

**Comment by jbreams** [comment]
I've been thinking about a default option for the timeout value - when I was writing this, I thought people would set the interval to be much higher than the timeout. So you send a PING message once every 10 seconds, but you would want a response within 1 second. Setting it to a fixed value 2-3 times the interval would mean that you'd have to send PING messages very frequently if you want to disconnect on high latency. But I guess 2x the interval is a reasonable default because otherwise there's no timeout at all (it will send PINGs without expecting any answer). I'll work on setting this default and updating the docs.

**Pull request merged**
