### PR TITLE
Add 'Peer-Address' property to connection metadata

### PR DESCRIPTION
**Pull request by rodgert**
Allows non-C/C++ based clients easy access to the peer's IP address via
zmq_msg_gets(&msg, "Peer-Address") instead of zmq_msg_get(&msg, ZMQ_SRCFD)
followed by calls to getpeername and getnameinfo

### CODE REVIEW

**Comment by metadings** [comment]
Hell is that cool...

**Comment by xaqq** [comment]
This is a nice addition.
Could you please push an additional commit with documentation ?

Thanks

**Comment by xaqq** [comment]
Haha I missed the  `+    Peer-Address` in the doc file. I did look at your previous PR though :p

Anyway the documentation is now very clear, thanks :).

**Comment by rodgert** [comment]
Thanks! I just noticed I made a typo though in my earlier doc commit...new PR inbound :)

**Comment by pebbe** [comment]
Does this work for all messages, or only for messages that got processed by the ZAP service?

**Comment by rodgert** [comment]
It works for all TCP sockets

**Comment by rodgert** [comment]
For all messages from TCP transprt

**Pull request merged**
