### PR TITLE
Problem: No CI for mingw64

### PR DESCRIPTION
**Pull request by chymanfx**
Solution: Adding CI support for mingw64 to appveyor.yml

Reason: To help address the following issues:
  Several checks fail under 64-bit MinGW on Windows when running make check #3185

Notice: I also did some "if" adjustments to enhance future changes for the different platforms and tried to improve the style. Hope that helps.

### CODE REVIEW

**Comment by bluca** [comment]
Doesn't seem to be working:

```
Error parsing appveyor.yml: (Line: 156, Col: 13, Idx: 6785) - (Line: 157, Col: 11, Idx: 6819): While parsing a block mapping, did not find expected key.
```

**Comment by chymanfx** [comment]
Yes, I saw that, I put the comment above now, sorry.

**Comment by bluca** [comment]
Still unhappy:

```
-- The C compiler identification is Clang 6.0.0
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeDetermineCompilerId.cmake:771 (message):
  The Clang compiler tool
    "C:/Program Files/LLVM/bin/clang.exe"
  targets the MSVC ABI but has a GNU-like command-line interface.  This is
  not supported.  Use 'clang-cl' instead, e.g.  by setting 'CC=clang-cl' in
  the environment.  Furthermore, use the MSVC command-line environment.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeDetermineCCompiler.cmake:113 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)
  CMakeLists.txt:4 (project)
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/projects/build_libzmq/CMakeFiles/CMakeOutput.log".

```

**Comment by chymanfx** [comment]
Hmm, it seems like the other compilers in the PATH interfere here in the mingw64 build.
I set CC=gcc and CXX=g++ as suggested in the cmake documentation.

**Comment by bluca** [comment]
Still borken:

```
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeDetermineCCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CC:
  gcc.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program. 
-- Configuring incomplete, errors occurred!
See also "C:/projects/build_libzmq/CMakeFiles/CMakeOutput.log".
```

**Comment by chymanfx** [comment]
With my path I refer to the appveyer documentation at: https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin

What Software / Build worker image do we have? Visual Studio 2013 / 2015 / 2017 ?
I thought what is set in line 7:  os: Visual Studio 2013

How can I check what is installed?

**Comment by bluca** [comment]
I thought so too, but I'm not a MS/Appveyor expert sorry - @sigiesec any idea?

**Comment by sigiesec** [comment]
The default is the Visual Studio 2015 image, the Visual Studio 2013 is only used for specific builds IIRC. I think in the build log you can see somewhere near the beginning which image is used. I am on vacation right now, hope this helps a bit.

**Comment by sigiesec** [comment]
Maybe the problem is that you need to install gcc for mingw? For cygwin, it was necessary to install some more packages.

**Comment by chymanfx** [comment]
Thank you, for your input. I will try to use mingw64 from msys2, I found some instructions which make things easier.

**Comment by bluca** [comment]
```
if "%PLATFORM%" == "mingw64" ( cmake --build . -- -j5 cp lib/libzmq-5.dll bin )
make: *** No rule to make target 'cp'.  Stop.

```

**Comment by bluca** [comment]
better but it fails to build docs now:

```
asciidoc: FAILED: manpage document title is mandatory
asciidoc: FAILED: manpage document title is mandatory
[ 44%] Generating zmq_plain.html
make[2]: *** [CMakeFiles/libzmq.dir/build.make:254: doc/zmq_poller_add.html] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/libzmq.dir/build.make:262: doc/zmq_poller_destroy.html] Error 1
[ 44%] Generating zmq_poller_modify.html
[ 45%] Generating zmq_poller_add_fd.html
[ 45%] Generating zmq_poller_add.html
asciidoc: FAILED: manpage document title is mandatory
make[2]: *** [CMakeFiles/libzmq.dir/build.make:258: doc/zmq_poller_add_fd.html] Error 1
asciidoc: FAILED: manpage document title is mandatory
asciidoc: FAILED: manpage document title is mandatory
make[2]: *** [CMakeFiles/libzmq.dir/build.make:266: doc/zmq_poller_modify.html] Error 1
make[2]: *** [CMakeFiles/libzmq-static.dir/build.make:258: doc/zmq_poller_add_fd.html] Error 1
make[2]: *** Waiting for unfinished jobs....
asciidoc: FAILED: manpage document title is mandatory
make[2]: *** [CMakeFiles/libzmq-static.dir/build.make:254: doc/zmq_poller_add.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:178: CMakeFiles/libzmq.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Generating zmq_poller_destroy.html
asciidoc: FAILED: manpage document title is mandatory
make[2]: *** [CMakeFiles/libzmq-static.dir/build.make:262: doc/zmq_poller_destroy.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:252: CMakeFiles/libzmq-static.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I think it would be fine to skip the docs build entirely

**Comment by chymanfx** [comment]
Yep, will do that.

The workaround for copying dll seems to not be necessary any more, at least for cygwin64:
`843  [ 32%] Linking CXX shared library bin/libzmq-5.dll`
Will remove that.

**Comment by bluca** [comment]
still seems to be built? strange

**Comment by chymanfx** [comment]
CMakeLists.txt has the following section:

```
cmake_dependent_option (WITH_DOC "Build Reference Guide documentation (requires DocBook)" ON
"PYTHONINTERP_FOUND;ASCIIDOC_FOUND" OFF)
```
According to https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html:
> ==CMakeDependentOption==
> 
> Macro to provide an option dependent on other options.
> 
> This macro presents an option to the user only if a set of other conditions are true. When the option is not presented a default value is used, but any value set by the user is preserved for when the option is presented again.

in our case the default value is used, because the option is not presented. Thus it ignores my -D WITH_DOC="OFF" flag.

Would you consider to present the option in CMakeLists.txt to make it available? This would give the user possibility to chose and would resolve my issue here.

**Comment by bluca** [comment]
sure

**Comment by chymanfx** [comment]
Or perhaps we can fix the docs...

**Comment by chymanfx** [comment]
I think I know the reason why asciidoc complains: it complains those pages, that are just symlinks to others. Windows likely doesn't handle the symlinks correctly.

I am very new to github, I guess I need some help here, either with the cmake file or the docs...

I have read Peter's books and I appreciate his work and that of you all very much!

**Comment by bluca** [comment]
I would suggest fixing cmake - I suspect it's going to be much easier than making sense of the difference between symlinks handling...

**Comment by chymanfx** [comment]
Sorry, I accidentally forgot to put a commit message on my last change. Is it possible to edit the commit message and put the comment above in it?

I tried different ways to expose the option in cmake, but I didn't get to work transparently enough.  I decided for a minimal change to disable the docs in Windows with the existing statement, hope it works now.

**Comment by bluca** [comment]
Great work, thanks - good enough for merging now. Don't worry about the commit message, I squashed anyway

**Comment by bluca** [comment]
@chymanfx could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by chymanfx** [comment]
Permission to Relicense under MPLv2 or any other OSI approved license chosen by the current ZeroMQ BDFL

I happily grant permission to
relicense its copyrights in the libzmq C++ library (ZeroMQ) under the
Mozilla Public License v2 (MPLv2) or any other Open Source Initiative
approved license chosen by the current ZeroMQ BDFL (Benevolent
Dictator for Life).

The portion of the commits made by the Github handle "chymanfx", are
not copyrighted in any way.
Chyman2019/08/12

**Comment by bluca** [comment]
Thank you!

**Pull request merged**
