### PR TITLE
Fix coverage job and appveyor job

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by somdoron** [comment]
Do you want to wait for appveyor or should I merge?

**Comment by somdoron** [comment]
We should consider Github actions, Appveyor is so slow it becomes irrelevant...

**Comment by bluca** [comment]
Let's wait, just to make sure

**Comment by bluca** [comment]
> We should consider Github actions, Appveyor is so slow it becomes irrelevant...

Yes, that would be good

**Pull request merged**
