### PR TITLE
Problem: formatting issues in CI

### PR DESCRIPTION
**Pull request by bluca**
Solution: ignore tweetnacl.c and reformat the rest

### CODE REVIEW

**Comment by sigiesec** [comment]
Unfortunately I had no time to investigate this further yet.

**Comment by bluca** [comment]
Ok, no worries. Wanna merge this?

**Comment by sigiesec** [comment]
@bluca I now found that it is not due to differences between OSs, but between versions. clang-format from LLVM 5.0.0 appears to have some bug when formatting comments preceding preprocessor directives, and I was using a more recent version under Windows. I will check if 5.0.1 fixes the issue already.

**Comment by sigiesec** [comment]
5.0.1 still has the bug :(

**Comment by sigiesec** [comment]
I think this is the fix of the bug: http://llvm.org/viewvc/llvm-project?view=revision&revision=308882

**Comment by bluca** [comment]
Ah - so the version we have available on Travis is the wrong one? There is a 6.0 PPA that could be used:

http://apt.llvm.org/trusty/dists/

But then 6.0 is not really widely available yet:

https://packages.ubuntu.com/search?keywords=clang-format-6.0&searchon=names&suite=all&section=all
https://packages.debian.org/search?keywords=clang-format-6.0&searchon=names&suite=all&section=all

Only in unreleased versions of Debian and Ubuntu. What do we do? Wait until it's more widely available?

**Pull request merged**
