### PR TITLE
Enable loading of MSVC project

### PR DESCRIPTION
**Pull request by sunkin351**

### CODE REVIEW

**Comment by hintjens** [comment]
I'm going to ask you to re-do this pull request if you don't mind.

- when you do 'git pull', use 'git pull --rebase' to avoid the 'Merge' commit
- you still have conflicts in builds/msvc/vs2015/libzmq/libzmq.vcxproj.filters
- I'm not sure why you're removing the UDP classes, which I added to all VS project files

Let me ask why you're removing the UDP classes from the build?

**Comment by bluca** [comment]
It's very useful to set git pull to always rebase automatically with this command:

```git config --global pull.rebase true```

With most workflows, especially when using GitHub, that's what you want in most cases when you pull.

**Comment by sunkin351** [comment]
Can someone tell me how to access this repository with pull instead of my fork?

**Comment by hintjens** [comment]
git remote add upstream https://github.com/zeromq/libzmq
git pull --rebase upstream master

**Comment by sunkin351** [comment]
Is that the recommended way to do it on github desktop?

**Comment by sunkin351** [comment]
Like, is there a way to directly update my fork without going through my local repository?

**Comment by hintjens** [comment]
:-) You need to read some background materials on git. Start here, maybe:
http://zeromq.org/docs:contributing

Learn to use the command line, it is worthwhile.

**Comment by bluca** [comment]
Github does not automatically sync forks (Stash by Atlassian does).

**Comment by sunkin351** [comment]
Sorry for being an inquisitive idiot, I am relatively new to this and wish to help.

**Comment by bluca** [comment]
Don't worry about it! I think I speak for everyone if I say that we are more than happy to help :-)

**Comment by hintjens** [comment]
@sunkin351 no apologies! You're learning, and we all go through this.

You can read more on how to use git, at http://scalablec.com, a book I'm working on.

**Pull request closed without merging**
