### PR TITLE
[WIP, RFC] Problem: Relevant events on sockets are discarded

### PR DESCRIPTION
**Pull request by jean-airoldie**
Solution: Introduce notification message using `msg_t` to forward these relevant events to the user.

See #3658.

# RFC
The following is a informal rfc so that I can better understand what is involved in such changes.

# Definitions used in this doc
* `server` = a socket which acts as a bound endpoint
* `client` = a socket which connects to a `server`

# Frontend changes

## Add `zmq_connect_peer` function.
This `zmq_connect_peer` function is functionally the same as `zmq_connect`, except
it returns a `routing_id` used to refer to the connection with the peer. This `routing_id` will be
used by notifications to refer to this peer. A `routing_id` of `0` means an
error occured.

## Add `ZMQ_FILTER_NOTIF` sockopt
The `ZMQ_FILTER_NOTIF` sockopt is used to configure what event notifications
should be received by the user. This socket takes a `uint64_t` bitmask,
which defaults to 0 (no notifications). See `NotifType` for
the list of possible events.

## Add `zmq_msg_notif` function.
This `zmq_msg_notif` function can be used to retreive the `NotifType` of
a message. A returned value of `-1` means that the message is not a notification.

## NotifType
These are the possible notifications events. Note that each of these is a bitflag.
* `ZMQ_NOTIF_CONNECTED` means a connection of a `client` was established with
    a remote `server`. The `routing_id` of the message is used to refer to
    the specific `server`.
* `ZMQ_NOTIF_DISCONNECTED` means a connection of a `client` with a remote
    `server` was closed. The `routing_id` of the message is used to refer to
    the specific `server`.
* `ZMQ_NOTIF_CONNECTION_ACCEPTED` means a `server` accepted a connection from a
    remote `client`. The `routing_id` of the message is used to refer to the specific `client`.
* `ZMQ_NOTIF_CONNECTION_CLOSED` means a connection accepted by the `server` from
    a remote `client` was closed. The `routing_id` of the message is used to
    refer to the specific `client`.
* `ZMQ_NOTIF_JOINED` means a remote `DISH` connected to a `RADIO` joined a `group`.
    The `group` of the message is used to refer the specific grouped that was joined.
* `ZMQ_NOTIF_LEAVED` means a remote `DISH` connected to a `RADIO` leaved a `group`.
    The `group` of the message is used to refer the specific grouped that was leaved.
* `ZMQ_NOTIF_HANDSHAKE_FAILED` means a ZAP handshake of a `client` with a
    remote `server` failed. The `routing_id` of the message is used to refer
    to the specific `server`. The `group` of the message is a `HandshakeFailureDetails`.
    See `HandshakeFailureDetails` for details.

## HandshakeFailureDetails
A handshake failure details is used to give details on the type of handshake failure.

```c
enum HandshakeFailureType {
    no_details = 0,
    protocol = 1,
    auth = 2,
};

struct HandshakeFailureDetails {
    HanshakeFailureType type;
    // if HandshakeFailureType::no_details, then code is an errno.
    // if HandshakeFailureType::protocol, then code is a ZMQ_PROTOCOL_ERROR_*
    // if HandshakeFailureType::auth, then code is a ZAP status code (i.e. 300, 400, 500).
    int code;
}
```
# Implementation

## zmq_connect_peer
???. Basically a socket would need to assigne a `routing_id` to each connection, but I don't know how that would be implemented.

## zmq_msg_notif
Check if the msg_type is `type_notif` then return the `NotifType` stored in the union. Else return -1 with EINVAL.

## ZMQ_NOTIF_FILTER sockopt
Add a notif_filter field to the socket options that will be used as a mask, similarly to how `zmq_socket_monitor` is implemented.

## notification msg format
Create a new msg_type::type_notif as well as a new message union. The message union has to contain a `NotifType`, a `group` and a `routing_id`.

## notification queue
??? Unsure how that would be implemented.

## notification mechanism
This would be very similar to how zmq_monitor is currently implemented. In each location where a relevant event occurs:
* Check the `notif_filter` bitflag so see if the notification is activated
* If it is, create a notification msg_t and set the appropriate field depending on the `NotifType`
* Queue the message to the notification queue.

## notification retrieval mechanism
When calling `recv` on a socket, check the notification queue first. If it contains a notification,
return it, otherwise operate as normal.

## Unresolved questions
* Should there be a notification for when a `server` denies a connection (handshake failure)?
* How should zmq_connect_peer be implemented?
* How should the notification queue be implemented?
* Should this mechanism be limited to DRAFT socket types?

### CODE REVIEW

**Comment by somdoron** [comment]
My idea is that all notification will be generated at the user thread, at least initially, that will limit the number of events that can be generated.

For the first phase I would try to support SERVER only with ATTACHED and TERMINATED events.
At the user thread we can distinguish between connect and accepted, and I would avoid that for now.

So ATTACHED/TERMINATED will replace the CONNECTED,DISCONNECTED,ACCEPTED and CLOSED.

At the moment we cannot support the HANDSHAKE_FAILED at the user thread side as well.

**Comment by somdoron** [comment]
Let's continue by finishing the Msg changes.
Those would be:
* Add another union case to the msg union: https://github.com/zeromq/libzmq/blob/master/src/msg.hpp#L212, for the notif type we need the base fields plus the notif_type. (it should be after metadata, and the following unused should set correctly).
* Add init_notif function to the class, which accept the notification type and initialize the msg.
* Add the notif method (msg class) and zmq_msg_notif (zmq.h & zmq.cpp, should be a draft).

**Comment by jean-airoldie** [comment]
What's the advantage in generating the events in the user thread as opposed to the event loop thread like how the socket_monitor API is implemented?
https://github.com/zeromq/libzmq/blob/69e451c1faa97c08ae7ac34bb4f948f7dfbc3472/src/stream_engine_base.cpp#L584

**Comment by somdoron** [comment]
> What's the advantage in generating the events in the user thread as opposed to the event loop thread like how the socket_monitor API is implemented?

The monitoring socket is a hack (I wish I could remove it), it is not thread-safe and if you would have more than one background thread it would fail, moreover, some of the events are generated at the user thread and some at the io thread (or at least it used to be like that), which is a violation of socket usage.

If we would enqueue the events into the msg pipe it would count for the watermark, and we don't want that.

The correct way to do it is to generate all the events at the user thread, in order to support events that we currently cannot generate at the user thread we should use commands.
Howevet, that is a little more advanced and we use it eventually.

Come for the zeromq hackathon, we could work on the commands for delivring other types of events.

**Comment by somdoron** [comment]
Regarding generating the events for SERVER socket:
1. We first need a queue for the events, so add std::queue notifications.
2. On xattachpipe and terminated insert notifications to the notifications queue.
3. On xrecv, before recv from a fq.recv first try to dequeue a notification.

**Comment by jean-airoldie** [comment]
> Come for the zeromq hackathon, we could work on the commands for delivring other types of events.

I'll consider it.

**Comment by bluca** [comment]
No activity for 6 months on this. Is work going to resume soon, or should I close it for now?

**Comment by jean-airoldie** [comment]
I won't work on it.

**Pull request closed without merging**
