### PR TITLE
Code style improvements

### PR DESCRIPTION
**Pull request by sigiesec**

### CODE REVIEW

**Comment by bluca** [comment]
All the *nix builds are failing:

```
../src/err.cpp: In function ‘void zmq::zmq_abort(const char*)’:
../src/err.cpp:85:27: error: ‘LIBZMQ_UNUSED’ was not declared in this scope
     LIBZMQ_UNUSED (errmsg_);
```

Missing include of macros.hpp I suppose

**Comment by sigiesec** [comment]
Should be fixed now :)

**Comment by bluca** [comment]
Some of the Windows builds are failing to compile as well, want to have a look?

**Comment by sigiesec** [comment]
Argh, sorry for being so careless, will give it a look

**Comment by bluca** [comment]
no worries

**Comment by sigiesec** [comment]
Now both travis and appveyor should be fine. The Debug tests on Appveyor are failing, but that's not new :( I just opened #3210 to investigate that.

**Pull request merged**
