### PR TITLE
Problem: backward incompatible change to NULL with ZAP

### PR DESCRIPTION
**Pull request by bluca**
Solution: fix it like for other mechanism, add test

### CODE REVIEW

**Comment by bluca** [comment]
@sigiesec when you have a sec could you please have a look and see if  I missed something?

**Comment by sigiesec** [comment]
@bluca I gave it a quick look. Looks good from my point of view :)

**Comment by bluca** [comment]
OK - I'll then do a revert of the recent changes to STABLE API, do a 4.2.5 bugfix only so that pyzmq can get unblocked, and then re-instate 4.3.0

**Comment by sigiesec** [comment]
https://developercommunity.visualstudio.com/content/problem/220882/unexpected-c2610-error.html?childToView=221696#comment-221696

**Pull request merged**
