### PR TITLE
Problem: term "identity" is confusing

### LINKED ISSUE #805: "Identity" concept is confusing and misnamed
This concept has always been confusing and misnamed. This is especially visible when we do authentication. What this concept actually does is define a routing name. I'm not sure what a better name than "identity" would be, but would like to discuss this.

### PR DESCRIPTION
**Pull request by sigiesec**
Solution:
- renamed to "routing id"

This is a fixed version of #2743 

Fixes #805

### CODE REVIEW

**Comment by sigiesec** [comment]
If there are any issues with this PR, please do not merge it. It is much easier to amend something before it is merged than after that.

**Comment by bluca** [comment]
I'll do a pass with ACC tomorrow

**Comment by sigiesec** [comment]
What is ACC?

**Comment by bluca** [comment]
abi-compliance-checker: https://lvc.github.io/abi-compliance-checker/

@somdoron I did a quick check and everything looks fine to me

**Comment by sigiesec** [comment]
@somdoron, @bluca Any objections against merging this?

**Comment by bluca** [comment]
None, looks good to me, but I've seen you requested a review from @somdoron so was waiting for that

**Comment by sigiesec** [comment]
@somdoron Is there any chance that you have a look at the changes, so this can be taken further?

**Comment by sigiesec** [comment]
So, now for the second time today I have conflicts in this PR. I tried to rebase this, but I gave up. Can someone else maybe do this?

Since this contains changes at quite a lot of places, it should be reviewed and merged real soon.

**Comment by sigiesec** [comment]
@bluca If @somdoron has no time to do the review now, maybe it is better in this case to merge it soon, since it changes so many files. I needed to rebase and resolve conflicts twice today already. The review can be done later on then.

**Comment by bluca** [comment]
Sure, that's reasonable. I'll let the CI runs at least on Linux and Windows (OSX is completely overloaded it seems) and then I'll merge, sorry for the wait.

**Pull request merged**
