### PR TITLE
more checks for parameters of API functions

### PR DESCRIPTION
**Pull request by niXman**

### CODE REVIEW

**Comment by bluca** [comment]
@niXman could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by niXman** [comment]
@bluca Hi,
sorry, but I don't understand how can I send a new pull request which that changes. Can you explain please?

**Comment by bluca** [comment]
@niXman create a new file by copying the template and fill it with your name/username: https://github.com/zeromq/libzmq/blob/master/RELICENSE/templates/relicense-template-mplv2-any-osi.txt

It's also fine if you just copy and paste it here as a comment, and I will take care of committing it to the repository for you.

Thanks!

**Comment by niXman** [comment]
```
# Permission to Relicense under MPLv2 or any other OSI approved license chosen by the current ZeroMQ BDFL

This is a statement by niXman (github.nixman@pm.me)
that grants permission to relicense its copyrights in the libzmq C++
library (ZeroMQ) under the Mozilla Public License v2 (MPLv2) or any other 
Open Source Initiative approved license chosen by the current ZeroMQ 
BDFL (Benevolent Dictator for Life).

A portion of the commits made by the Github handle "niXman", with
commit author "niXman", are copyright of {{ name }} .
This document hereby grants the libzmq project team to relicense libzmq, 
including all past, present and future contributions of the author listed above.

niXman (github.nixman@pm.me)
2019/10/03
```

but I can't understand what `{{ name }}` means... I left it as is.

**Comment by niXman** [comment]
sorry for the delay :(

**Comment by bluca** [comment]
No problem at all - "name" means your name or username, I'll fill it in for you. Thanks!

**Pull request merged**
