### PR TITLE
Atomic operations for armv7a

### PR DESCRIPTION
**Pull request by tranthamp**
This commit implements atomic operations for the armv7a architecture
using gcc inline assembly.  This offers higher performance compared to
pthread mutexes.

Tested on an am3517 evm, clocked at 600MHz:
## ./inproc_thr 200 1000000

53-60K messages / sec, pthread mutexes
73-90K messages / sec, assembly atomic ops
## ./inproc_lat 200 1000000

average latency: 42.234 [us], pthread mutexes
average latency: 35.496 [us], assembly atomic ops

### CODE REVIEW

**Comment by bluca** [comment]
@tranthamp could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by bluca** [comment]
@tranthamp  another ping. Please consider helping us with the relicense. Thank you!

**Comment by bluca** [comment]
> @tranthamp could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

@tranthamp another ping. Please consider helping us, only takes a minute. Thanks!

**Comment by bluca** [comment]
@tranthamp could you please send a new pull request or an email with a relicense statement, or just leave a comment here with an ACK? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. We have now received multiple reports of projects being stopped in their tracks due to the custom license we use: https://github.com/zeromq/libzmq/issues/2376

Thank you!

**Comment by tranthamp** [comment]
@bluca my apologies for dragging my feet on this.  I just submitted a pull request with the relicense statement as requested.

**Comment by bluca** [comment]
Thank you!

**Pull request merged**
