### PR TITLE
TweetNaCL: add windows randombytes implementation

### PR DESCRIPTION
**Pull request by madebr**
This PR addresses the issue introduced by #1618 and noted by @ricnewton.

Changes in this PR:
- libsodium and tweetNaCL are enabled by default:
  * libsodium has the highest priority and will be used if found
  * if not found, tweetNaCL is used (if enabled)
- appveyor tests most relevant combinations
  * if you think that some combination can be removed/should be added. Let it be known!
- added randombytes and randombytes_close implementation for windows.
  * reference implementation: https://msdn.microsoft.com/en-us/library/windows/desktop/aa379942(v=vs.85).aspx
  * please review this function, because maybe the function can get stuck in a loop. 

Test of this PR: https://ci.appveyor.com/project/madebr/libzmq/build/build-31

Btw, shouldn't this repo enably appveyor CI?
So every commit and PR is tested automatically?

### CODE REVIEW

**Comment by madebr** [comment]
I just found out that libsodium can be built with both TweetNaCL and libsodium.
I thought that these libraries were exclusive.
Will address that in yet another PR...

**Comment by c-rack** [comment]
Thanks!

I have not heard about appveyor CI before, so I checked, found it free for open-source projects and – as we do not have CI for Windows yet – added libzmq to give it a try. Unfortunately, appveyor took my username and not the organization name in the URL. If anyone knows a better way or raises concerns regarding appveyor, please let me know.

https://ci.appveyor.com/project/c-rack/libzmq

**Comment by madebr** [comment]
czmq enabled it previous week

**Comment by c-rack** [comment]
Great, did not know about it... Now I am watching czmq repo, too :)
Any idea how we get the link changed to `zeromq` instead of `c-rack`?

**Comment by madebr** [comment]
I don't know for sure, but have a look at http://www.appveyor.com/docs/team-setup

> Account is an entity grouping all other resources like projects, environments and users.
> Account can have multiple projects and each project belong to a single account.
> Account may have a plan and subscription assigned. Another analogy for an account is
> organization.

**Comment by madebr** [comment]
@sappo created an account. see zeromq/czmq#1125

**Comment by c-rack** [comment]
Thanks. I have deleted my project then.
@sappo Would you mind to add libzmq with the zeromq account?
Next would be a PR which adds the badge I guess...

**Comment by sappo** [comment]
@c-rack sure I could do that, but I added all zeromq owners to the team. If you sign in to appveyor with github you should be able to add libzmq yourself. Can you verify that works,, please.

**Pull request merged**
