### PR TITLE
Fix some more code style issues

### PR DESCRIPTION
**Pull request by sigiesec**
See individual commits

### CODE REVIEW

**Comment by bluca** [comment]
I don't think I have seen this fail before:

```
Expected monitor event 400 but received 200
lt-test_monitor: ../tests/testutil_security.hpp:407: void expect_monitor_event(void*, int): Assertion `event == expected_event' failed.
```

Could you please double check?

**Comment by sigiesec** [comment]
@bluca Where did you see this?

**Comment by sigiesec** [comment]
Ah, got it, here: https://travis-ci.org/zeromq/libzmq/jobs/380740484#L1587

**Comment by sigiesec** [comment]
Hm, 200 would be ZMQ_EVENT_DISCONNECTED, and there are already some checks in test_monitor that handle this as optional on the server side, but not on the client side. I think this optional handling is only missing on the client side.

**Pull request merged**
