### PR TITLE
Problem: insufficient error handling relative to zap_connect.

### PR DESCRIPTION
**Pull request by evoskuil**
See also https://github.com/zeromq/libzmq/issues/2481

### CODE REVIEW

**Comment by evoskuil** [comment]
Unless I'm missing something, it looks like certain test cases expect zap_connect to succeed when it's failing.

**Comment by evoskuil** [comment]
Is the one test failure an actual issue?

**Comment by bluca** [comment]
That one is flacky on OSX, don't worry about it

**Comment by evoskuil** [comment]
I keep forgetting which one that is.

**Comment by bluca** [comment]
IIRC the _many_sockets and _shutdown_stress are flacky on OSX and Windows, and on Windows one of the HWM is flacky too.
With DRAFT enabled the test_poller is flacky everywhere, but it might be because of tcp ports overload

**Comment by bluca** [comment]
Anyway thanks for catching the test problem and for improving the ZAP error handling, it's much better now!

**Comment by evoskuil** [comment]
Cool, thanks - and no, glad to help.

**Pull request merged**
