### PR TITLE
problem: Tests are failing on windows

### PR DESCRIPTION
**Pull request by somdoron**
please let the CI run, I want to check if this fixed the problem

### CODE REVIEW

**Comment by hitstergtd** [comment]
@somdoron,
This will "fix it", in the sense that now you are using a non-wildcard address. The question is why aren't wildcard addresses working at all. I believe your fix is masking that issue.

**Comment by somdoron** [comment]
not really, I still using wildcard addresses.

The problem is that on windows you cannot connect to 0.0.0.0 (I'm not sure what the behavior on linux). So I'm still using the wildcard on the bind but for the connect I'm using localhost. The test is for unbind wildcard address, which I'm still testing.

**Comment by somdoron** [comment]
not really, I still using wildcard addresses.

The problem is that on windows you cannot connect to 0.0.0.0 (I'm not sure what the behavior on linux). So I'm still using the wildcard on the bind but for the connect I'm using localhost. The test is for unbind wildcard address, which I'm still testing.

**Comment by somdoron** [comment]
@hitstergtd the bottom line is that we are still checking unbind of wild card, I just changed the connected address to solve specific problem on windows, the binding is still on wildcard addresses.

**Comment by bluca** [comment]
On Linux (and I believe *nix in general) connecting to localhost.

But more importantly: shouldn't ZMQ_LAST_ENDPOINT return an actual address, rather than INADDR_ANY?

**Comment by somdoron** [comment]
@bluca I don't think so, when you are binding on * you actually bind all interfaces, so ZMQ_LAST_ENDPOINT return INADDR_ANY, which seems right.

**Comment by somdoron** [comment]
So the different behavior is, on linux connecting to 0.0.0.0 connect to localhost, on windows it just fail. So I just changed it so on windows it will connect to 127.0.0.1.

**Comment by hitstergtd** [comment]
@somdoron - you are absolutely spot on.

**Comment by bluca** [comment]
Ah yes, it makes sense thinking about it.

**Comment by hitstergtd** [comment]
Next time @bluca, we will just wildcard all issues to @somdoron (just kidding). :-)
@somdoron Thanks again!

**Comment by somdoron** [comment]
This can be merged. Tests are fixed, now the jenkins failing on those:
48 - test_thread_safe (Timeout)
	 61 - test_xpub_manual (Failed)
	 63 - test_timers (Failed)

**Comment by somdoron** [comment]
@hitstergtd you welcome :-)

**Pull request merged**
