### PR TITLE
[WIP] Problem: ZMTP 3.1 PING Context not implemented

### PR DESCRIPTION
**Pull request by bluca**
Solution: add it

Fixes: https://github.com/zeromq/libzmq/issues/3061

@sigiesec do you have time to give me a hand with Windows, please?

I really don't understand what the problem is - sometimes, there is no data coming from the raw tcp read in the mocked test. Any clue?

### CODE REVIEW

**Comment by sigiesec** [comment]
I will give it a look today... Provided my train happens to have a working internet connection ;)

**Comment by sigiesec** [comment]
I think this is simply a timing issue. If the mock peer takes too long, the other peer has already closed the connection, which is a valid behaviour. By increasing the ZMQ_HEARTBEAT_IVL sufficiently, this should go away.

Note: in my branch https://github.com/sigiesec/libzmq/tree/ping-context I migrated the tests to unity.

**Comment by bluca** [comment]
But in the mock test there is no heartbeat - and that's the one failing? I've also tried to have it loop forever, and it just gets stuck and never receives any data

**Comment by sigiesec** [comment]
What do you mean by "in the mock test there is no heartbeat"? In the failing test case (with mock_ping == true), heartbeats are activated:
https://github.com/sigiesec/libzmq/blob/74fb2f433a74eb6dbef5f52ac3a10d03ce9ef90d/tests/test_heartbeats.cpp#L226

**Comment by sigiesec** [comment]
Right. Hm. Will check again.

**Comment by sigiesec** [comment]
@bluca I opened a new PR #3097 from my branch, which also contains the test framework migration. Ok to close this one? I also have found some trace of how this fails if it fails (but not yet why).

**Pull request closed without merging**
