### PR TITLE
Deletion of zmq_utils.cpp

### PR DESCRIPTION
**Pull request by sunkin351**
The number of commits I am pushing from other people concern me, but I have small things to share in order to make this buildable on Windows once more.

I expect that zmq_utils.cpp is no longer needed.

### CODE REVIEW

**Comment by sunkin351** [comment]
Please reject if either zmq_utils.h or *.cpp are being added by this merge.

**Comment by hintjens** [comment]
Your pull request contains other peoples' commits. This happens when your repositories get messed up. I suggest you stop making commits to libzmq for now, until you have improved your git skills.

Also we still use zmq_utils.cpp; the methods are exported by zmq.h.

**Comment by sunkin351** [comment]
I could not build ZMQ with zmq_utils.cpp included in the project... Pls fix this if you still need the file.

**Comment by hintjens** [comment]
What build error are you getting?

(We cannot simply remove pieces of the library that people are depending
on.)

**Pull request closed without merging**
