### PR TITLE
Improvements and fixes for performance of PUSH/PULL in local_thr and rem...

### PR DESCRIPTION
**Pull request by ambitslix**
...ote_thr.
- option to set number of zmq threads on the command line for local_thr
- option to set number of zmq_threads and workers in remote_thr
- option to set SND/RCV buffer sizes on command line
- option to set whether to PUSH/PULL on command line
- option to set to use zmq_recv or zmq_msg for transfer on command line
- better timing function
- corrected and improved throughput reporting
- HWM and DELAY socket options

### CODE REVIEW

**Comment by bluca** [comment]
@ambitslix could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by bluca** [comment]
@ambitslix  another ping. Please consider helping us with the relicense. Thank you!

**Comment by bluca** [comment]
> @ambitslix could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

@ambitslix another ping. Please consider helping us, only takes a minute. Thanks!

**Comment by bluca** [comment]
@ambitslix could you please send a new pull request or an email with a relicense statement, or just leave a comment here with an ACK? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. We have now received multiple reports of projects being stopped in their tracks due to the custom license we use: https://github.com/zeromq/libzmq/issues/2376

Thank you!

**Comment by hoditohod** [comment]
Hi Luca,
I actually contacted Mark some time ago and he sent a relicense statement in PR #4083.

**Comment by bluca** [comment]
Oh! My bad, the list was not updated then. Thanks and sorry for the noise!

**Pull request merged**
