### PR TITLE
fix CMP0053 warning with cmake 3.1

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by bluca** [comment]
@xantares 
could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by bluca** [comment]
@xantares another ping. Please consider helping us with the relicense. Thank you!

**Comment by xantares** [comment]
hi, I'm fine with the MPL2 relicense

**Comment by bluca** [comment]
> hi, I'm fine with the MPL2 relicense

@xantares thank you! I have converted that statement into this grant: https://github.com/zeromq/libzmq/pull/3803/commits/f6de0dcafab1d251a85f4862066d70f235c6d772

**Pull request merged**
