### PR TITLE
Compatible with c99 stdint.h in VS2008

### PR DESCRIPTION
**Pull request by ccpaging**
```
Problem: Can not compile in Visual Studio 2008 since without 'stdint.h'

Solution: Add necessary define in 'platform.hpp'
```

Please avoid sending a pull request with recursive merge nodes, as they
are impossible to fix once merged. Please rebase your branch on
zeromq/libzmq master instead of merging it.

git remote add upstream git@github.com:zeromq/libzmq.git
git fetch upstream
git rebase upstream/master
git push -f

In case you already merged instead of rebasing you can drop the merge commit.

git rebase -i HEAD~10

Now, find your merge commit and mark it as drop and save. Finally rebase!

If you are a new contributor please have a look at our contributing guidelines:
[CONTRIBUTING](http://zeromq.org/docs:contributing)

### CODE REVIEW

**Comment by ricnewton** [comment]
Merged build triggered.

**Comment by ricnewton** [comment]
Merged build started.

**Comment by bluca** [comment]
Sorry but this breaks cmake builds.

Also it's already been done here:

https://github.com/zeromq/libzmq/blob/d2b6985028b25fffd0c07a18fbb660dcb5e2951f/include/zmq.h#L97

**Comment by ccpaging** [comment]
@bluca 

Thanks. I should try again.

**Pull request closed without merging**
