### PR TITLE
problem: push-pull socket types are not thread safe

### PR DESCRIPTION
**Pull request by somdoron**
solution: add new socket types, scatter and gather which are thread safe.

@hintjens thought it might make you smile a little.

### CODE REVIEW

**Comment by hitstergtd** [comment]
@somdoron - just wondering - what specifically makes them thread-safe?

**Comment by hitstergtd** [comment]
@somdoron 
I see `test_large_msg` was added to `.gitignore` but don't see that file anywhere?

**Comment by somdoron** [comment]
First is rejecting multipart messages. Then the implementation (mutex) is already in socket_base, so the the last parameter to the base ctor enable the thread safety

**Comment by hitstergtd** [comment]
@somdoron - Thanks!

**Comment by hitstergtd** [comment]
@somdoron - did you need to add `test_large_msg` to the pull?

**Comment by somdoron** [comment]
Regarding the gitignore, I added all the stuff that shouldn't be commited as and git status as show as new files. Bottom line when adding new test the executable should be added to ignore, someone didn't do it so I just added it

**Comment by somdoron** [comment]
Or maybe it deleted test that only exist in my machine?

**Comment by somdoron** [comment]
You are right, it only on my machine, i will fix that

**Comment by hitstergtd** [comment]
Thanks! I just re-checked my tree just to be sure as well.

**Comment by hintjens** [comment]
cool cool cool!

**Comment by hitstergtd** [comment]
@somdoron - I will pull it once you fix the `test_large_msg` addition.

**Comment by somdoron** [comment]
@hitstergtd fixed

**Comment by hintjens** [comment]
@somdoron I'm so impressed :)

**Comment by somdoron** [comment]
Thanks :)

Only the pair socket type is now missing... You had a plan to use client-server instead, do you we need the thread safe pair?

**Comment by hintjens** [comment]
Well, we can at least emulate pair-to-pair with client-to-server. This suggests we do not need a threadsafe pair equivalent. We can also do more interesting things in the only use case I know for pair, which is actors. I.e. start up internal services that are accessible from any thread in the process. Like a logging actor, or a permissions actor.

**Comment by somdoron** [comment]
If we don't want req-res we can just use same client for threads accessing the actor. 

if we need req-res we have few options:
1. If we want req-res each thread or user need it is own client socket, we can create those on the spot, thread safe socket is less expensive (no file descriptor to create, only mutex), but still can be expensive, we can some kind of pool. 

2. Any user of the actor must create a reference, so the api can be:

```C
zactor_ref_t* zactor_ref_new (zactor_t *actor);
zactor_ref_t  zactor_ref_send (zactor_ref_t *self, zframe_t **frame_p);
zframe_t* zactor_ref_recv (zactor_ref_t *self);
```

3. Add zmq_send_recv that is atomic and send and then wait for message. Only issue with this is that it will block all other operations until the response is received.

**Comment by hintjens** [comment]
synchronous req rep should be called the "strange cousin" pattern. let's
never talk about him again.

**Pull request merged**
