### PR TITLE
fix: websocket url without path

### PR DESCRIPTION
**Pull request by mloy**
websocket urls without a path caused crash!

### CODE REVIEW

**Comment by somdoron** [comment]
@mloy can you add a test case to tests/ws_transport_test.c and a relicense file? You can pick one of the templates https://github.com/zeromq/libzmq/tree/master/RELICENSE/templates

**Comment by mloy** [comment]
@somdoron cmake does not build ws_transport_test. I seem to be missing some configuration.

**Comment by mloy** [comment]
I added a test but I would like to build and execute it locally before pushing it into my pull request.

**Comment by mloy** [comment]
I ran into horrible merge conflicts. I created a new pull request (#3782) with the same fix plus test and relicense file.

Sorry for the trouble!

**Comment by mloy** [comment]
I'll close this request!

**Pull request closed without merging**
