### PR TITLE
Bzimmerman cmake

### PR DESCRIPTION
**Pull request by bzimmerman-qb**

### CODE REVIEW

**Comment by bzimmerman-qb** [comment]
Update cmake file

**Comment by hintjens** [comment]
Note that the cmake file is generated from project.xml via zproject. It says so quite clearly in the header. If you modify it by hand, your changes all get lost next time we regenerate it... 

See https://github.com/zeromq/zproject

**Comment by hintjens** [comment]
Note also I merged this anyhow; we can fix the breakage later. A heads-up that you will want to backport your changes to zproject.

**Comment by somdoron** [comment]
@bzimmerman-qb @hintjens the pull request is also breaking the windows build on jenkins (cannot find ws2)

image

**Comment by bzimmerman-qb** [comment]
This pull request was not meant to be merged with the master and instead go into a branch.  If the previous CMAKE file worked then this change can be reverted back.

**Comment by hintjens** [comment]
OK, please only make pull requests to master that you intend us to merge,
as that is what will happen. We don't use branches. Broken code shows
immediately (that's the goal).

**Comment by somdoron** [comment]
@bzimmerman-qb  should following pull request also be revered?

https://github.com/zeromq/libzmq/pull/1346

**Comment by somdoron** [comment]
@bzimmerman-qb sorry, it was never merged.

**Comment by bzimmerman-qb** [comment]
Sorry for the accidental submittable.  I have realized my mistake in the merging process and since been merging to the branch.

**Comment by bluca** [comment]
@bzimmerman-qb could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by bluca** [comment]
@bzimmerman-qb  another ping. Please consider helping us with the relicense. Thank you!

**Pull request merged**
