### PR TITLE
Problem: test_radio_dish triggers aliasing errors with some compilers

### PR DESCRIPTION
**Pull request by simias**
Since I can't reproduce the error locally I don't know if this actually fixes the problem but I though it was worth a try.

### CODE REVIEW

**Comment by bluca** [comment]
I've started a CentOS build here: https://build.opensuse.org/package/show/home:bluca:branches:network:messaging:zeromq:git-draft/libzmq

**Comment by simias** [comment]
Let's try with an union then

**Comment by bluca** [comment]
@simias this one's good!
But now clang-format is complaining:

```
--- a/tests/test_radio_dish.cpp
+++ b/tests/test_radio_dish.cpp
@@ -268,7 +268,8 @@ static const char *mcast_url (int ipv6_)
 #define IPV6_ADD_MEMBERSHIP IPV6_JOIN_GROUP
 #endif
 
-union sa_u {
+union sa_u
+{
     struct sockaddr generic;
     struct sockaddr_in ipv4;
     struct sockaddr_in6 ipv6;
@@ -391,8 +392,7 @@ static bool is_multicast_available (int ipv6_)
 
     msleep (SETTLE_TIME);
 
-    rc =
-      sendto (send_sock, msg, strlen (msg), 0, &mcast.generic, sl);
+    rc = sendto (send_sock, msg, strlen (msg), 0, &mcast.generic, sl);
     if (rc < 0) {
         goto out;
     }
```

**Comment by simias** [comment]
Sorry, fixed

**Pull request merged**
