### PR TITLE
problem: GNUTLS handshake is getting blocked because of timeout on some versions

### PR DESCRIPTION
**Pull request by somdoron**
Solution: disable handshake timeout

### CODE REVIEW

**Comment by somdoron** [comment]
This the gnutls line that causes the issue: on recent version:
https://github.com/gnutls/gnutls/blob/b9c965ecbcfe873b09cd4c854119c5d6dcb0a462/lib/record.c#L1302

```
ret = recv_headers(session, record_params, type, htype, &record, (!(session->internals.flags & 
    GNUTLS_NONBLOCK))?&ms:0);
```

and on version 3.3.0
https://github.com/gnutls/gnutls/blob/cd91840c564751924837ccdc9648d9a83a0b7601/lib/gnutls_record.c#L1182
```
ret = recv_headers(session, record_params, type, htype, &record, &ms);
```

The bottom line, previous versions call pull with timeout although the NON_BLOCK flag is set.
Newer versions fix that.
Any way to solve this, I'm not setting a timeout for the handshake.
We already have zeromq timeout for handshake.

**Comment by bluca** [comment]
@somdoron still getting stuck - note that it's the ws test, as these builds do not have gnutls:

https://build.opensuse.org/package/show/network:messaging:zeromq:git-stable/libzmq

**Comment by somdoron** [comment]
Yes, I know. It was wss test before that, somehow gnuTLS was present.

I'm working on the ws test now.

**Comment by bluca** [comment]
thanks!

**Comment by somdoron** [comment]
@bluca I tried to setup the same machine that failed (fedora) without success.
It seems like an assert, any chance I can get access to the `test-suite.log` file?
If not, can you print the file at the end of the build?

**Comment by somdoron** [comment]
it seems fedora always failed for the ws_transport test

**Comment by bluca** [comment]
@somdoron check here in a few minutes: https://build.opensuse.org/package/show/home:bluca:branches:network:messaging:zeromq:git-draft/libzmq

**Comment by somdoron** [comment]
it seems the cat test-suite.log is only running when make check is successful

**Comment by bluca** [comment]
@somdoron fixed - doesn't look like there's much in it https://build.opensuse.org/package/live_build_log/home:bluca:branches:network:messaging:zeromq:git-draft/libzmq/Fedora_30/x86_64

**Comment by somdoron** [comment]
Sorry, `tests/test_ws_transport.log` will have the information, but I will try to make a pull request that prints the log of failed tests.

**Comment by somdoron** [comment]
it seems `make check VERBOSE=1` will do the trick.

**Comment by somdoron** [comment]
The log is not detailed enough... anyway I can trigger build now, so I will stop bothering you for now..

**Comment by bluca** [comment]
no worries

**Comment by bluca** [comment]
@somdoron the test started failing again on all distros today (no idea why):

https://build.opensuse.org/package/show/network:messaging:zeromq:git-draft/libzmq

```
[  234s] ./config/test-driver: line 107:  8935 Alarm clock             "$@" > $log_file 2>&1
[  234s] FAIL: tests/test_wss_transport
```

Could you have a look please?

**Comment by somdoron** [comment]
Yes, will take a look today.

**Comment by somdoron** [comment]
fixed by https://github.com/zeromq/libzmq/pull/3734

**Pull request merged**
