### PR TITLE
Problem: Duplicated code

### PR DESCRIPTION
**Pull request by Cziken**
Solution: set_curve_key method in options_t struct with little
improvement in switch-case block

### CODE REVIEW

**Comment by bluca** [comment]
This change actually breaks CURVE, so I'm reverting it.

How did you test it?

**Comment by Cziken** [comment]
I've run tests from ci_build.sh, all of them passed so this is strange. I will take a look on it at monday :) sorry, I'm total noob in this project but I will try to track it down and fix it. Do you have crash or somewhere is Null instead of actual value?

**Comment by bluca** [comment]
you can check the test runs on linux osx and windows:

https://travis-ci.org/zeromq/libzmq/builds/184582112
https://ci.appveyor.com/project/zeromq/libzmq/build/build-924
https://libzmq.cloudapp.net/job/libzmq/1348/console

also a simple ```make check``` will show that it fails

**Comment by Cziken** [comment]
Maybe we can add this info about make check to docs? I'll fix this at Monday and open another pull req. Sorry for inconvenience and have a nice weekend! :)

**Comment by bluca** [comment]
It's already there https://github.com/zeromq/libzmq/blob/master/INSTALL#L69

**Comment by Cziken** [comment]
I was always too eager :( ok, thanks for the tip :)

**Pull request merged**
