### PR TITLE
If OPENPGM_FOUND is set, link to libpgm.

### PR DESCRIPTION
**Pull request by mbalmer**
This solves issue #4200

### CODE REVIEW

**Comment by bluca** [comment]
Please add a relicense statement as described in https://github.com/zeromq/libzmq/tree/master/RELICENSE - thanks

**Comment by mbalmer** [comment]
> Please add a relicense statement as described in https://github.com/zeromq/libzmq/tree/master/RELICENSE <https://github.com/zeromq/libzmq/tree/master/RELICENSE> - thanks
> 
Do you really consider a 9 lines diff in CMakeLists.txt a code contribution that needs a license?

**Comment by mbalmer** [comment]
>> Please add a relicense statement as described in https://github.com/zeromq/libzmq/tree/master/RELICENSE <https://github.com/zeromq/libzmq/tree/master/RELICENSE> - thanks
>> 
> Do you really consider a 9 lines diff in CMakeLists.txt a code contribution that needs a license?
> 

After all I do not (yet?) hold or claim any copyrights in an ZeroMQ code.  This was a mere bugfix.

Different story are my Lua bindings at https://github.com/arcapos/luazmq <https://github.com/arcapos/luazmq> and https://github.com/arcapos/mqlua <https://github.com/arcapos/mqlua>, but then these are not part of the ZeroMQ project.

**Comment by bluca** [comment]
> Please add a relicense statement as described in https://github.com/zeromq/libzmq/tree/master/RELICENSE <https://github.com/zeromq/libzmq/tree/master/RELICENSE> - thanks
> Do you really consider a 9 lines diff in CMakeLists.txt a code contribution that needs a license?

(probably?) not, but Github makes it very obvious when a first contribution is made, so it's easier to ask for it at that point, rather than tracking who sent it and who didn't if you then later submit a larger PR. I know it's annoying, but believe me, trying to get this relicensing sorted is orders of magnitude more work.

**Comment by mbalmer** [comment]
> Am 31.05.2021 um 11:54 schrieb Luca Boccassi ***@***.***>:
> 
> ﻿
> Please add a relicense statement as described in https://github.com/zeromq/libzmq/tree/master/RELICENSE https://github.com/zeromq/libzmq/tree/master/RELICENSE - thanks
> Do you really consider a 9 lines diff in CMakeLists.txt a code contribution that needs a license?
> 
> (probably?) not, but Github makes it very obvious when a first contribution is made, so it's easier to ask for it at that point, rather than tracking who sent it and who didn't if you then later submit a larger PR. I know it's annoying, but believe me, trying to get this relicensing sorted is orders of magnitude more work.
> 

Well, I have no plans to contribute code, I am a mere (long time) user of ZeroMQ, and if it does not build, I invest some time trying to find out what is wrong. Maybe WITH_OPENPGM should be added to the automated tests.

**Comment by mbalmer** [comment]
Are you not going to merge this?

**Comment by bluca** [comment]
Please add a relicense statement first as described in https://github.com/zeromq/libzmq/tree/master/RELICENSE - it's a few lines of text to copy/paste, it takes less than a minute. Thanks.

**Comment by mbalmer** [comment]
Not for a 9 line change in Makefile.

**Comment by mbalmer** [comment]
So stupid… And obviously not interested in solving problems…Am 06.06.2023 um 14:53 schrieb Luca Boccassi ***@***.***>:﻿
no permission given to distribute under MPL2, the relicensing is complete so this cannot be merged, closing

**Pull request closed without merging**
