### PR TITLE
Change out pipe state processing method

### PR DESCRIPTION
**Pull request by reza-ebrahimi**

### CODE REVIEW

**Comment by somdoron** [comment]
I think @bluca already solved that...

**Comment by somdoron** [comment]
Also, changing check write is problematic. The method is being used else where without calling check_hwm

Luca fix is simpler and does change pipe, which is the core of libzmq, I'm afraid to change it

**Comment by bluca** [comment]
I agree with Doron, thanks for the PR but I think it's better to avoid major refactors of these classes unless it's absolutely necessary, there's a lot of risk and not much reward

**Comment by reza-ebrahimi** [comment]
this is `check_hwm` body:

`bool full = hwm > 0 && msgs_written - peers_msgs_read >= uint64_t (hwm);`

and I placed following expression where above expression variables are changing, so calling  `check_hwm` multiple times will have same previous operation, is not?

and for reward, I think many places in zeromq have bad code and if you want to ignore them it will face zeromq with further development problems.

**Comment by reza-ebrahimi** [comment]
most of the zeromq class doesn't exposed to the outside world as an API and consider changes in code as API brokerage is not good idea, by the life time of zeromq ROUTER socket considered as one connected client and there is no API for resolving this problem #2319.

**Comment by somdoron** [comment]
@reza-ebrahimi changing behavior which can crash/effect users applications is API breakage.

The problem of changing the pipe class is that is used all over the code, from all socket types and also from the background IO thread. We cannot know what the full effect of changing the pipe class and should avoid if possible.

If there is a simpler solution which doesn't change the pipe class, we need to prefer it.

**Comment by somdoron** [comment]
@bluca solution is simpler and solve the problem, take a look here:
https://github.com/zeromq/libzmq/commit/a73d5cd6c683733eada457cfe44d4e2959da65d0

**Comment by bluca** [comment]
One of the issues of these classes being internal-only is that there's no direct unit (or module?) testing for them - so refactoring is very dangerous as we don't have any direct and immediate verification for correctness. This is why we need to be careful, and when there's a bug like in this case, trying to apply the smallest change possible is the safest course of action.

I believe it would be possible, however, to add module testing. Perhaps a selftest method inside the class itself, and a new small test binary built by automake without linking to the full libzmq shared library.
@reza-ebrahimi we are very grateful for your help on these issues, and if you would like to refactor these internal classes as you said, I would suggest starting by adding this module selftest functionality. As you I'm sure you know it's widely accepted as an engineering good practive to have comprehensive unit testing in place before engaging in refactoring.

**Pull request closed without merging**
