### PR TITLE
Problems: test_security_curve occasionally hangs or fails due to ECONNABORTED

### PR DESCRIPTION
**Pull request by bluca**
Solution: add missing flags parameter

Fixes https://github.com/zeromq/libzmq/issues/2658

### CODE REVIEW

**Comment by jimklimov** [comment]
Thanks, was it just a coding error, or two possible host-OS APIs to take care of? And why wasn't this caught by CI? Shoulda have tested all codepaths, eh ;)

**Comment by bluca** [comment]
Coding error on my side - the API is very new and only the latest version of libc supports it, so it's not used by travis

**Comment by sigiesec** [comment]
Great, hope this fixes the hang permanently :)
One Appveyor job now failed because of an error 106 == ECONNABORTED ... grr... this must probably be handled like EPIPE and ECONNRESET

**Comment by bluca** [comment]
Makes sense.

The only other left then is this:

```
test_garbage_server_key
count of ZMQ_EVENT_HANDSHAKE_FAILED_ENCRYPTION events: 2
test_garbage_client_public_key
count of ZMQ_EVENT_HANDSHAKE_FAILED_ENCRYPTION events: 1
test_garbage_client_secret_key
count of ZMQ_EVENT_HANDSHAKE_FAILED_ENCRYPTION events: 1
Ignored event: 800 (err = 32)
lt-test_security_curve: tests/test_security_curve.cpp:622: void test_curve_security_zap_unsuccessful(void*, char*, void*, void*, int, int): Assertion `1 <= zmq_atomic_counter_value (zap_requests_handled)' failed.
```

**Comment by sigiesec** [comment]
Hope to catch this last problem by #2663

**Comment by jimklimov** [comment]
Merged per discussion comments. Looking forward to having that fail fixed, though :)

**Comment by bluca** [comment]
@sigiesec ok I think we got them all now, right? Am I missing something?
I'll manually kick the CI a few times on my fork just to check

**Comment by sigiesec** [comment]
I think all things we have seen so far should be fixed now. Hope that nothing new turns up :)

**Comment by bluca** [comment]
Fantastic, thank you very much for your work!

**Comment by sigiesec** [comment]
I found one more issue I had already fixed in a branch. See #2664

**Pull request merged**
