### PR TITLE
Problem: appveyor binary archives do not contain import libraries

### LINKED ISSUE #3635: Missing .lib files in Windows .Zip downloads
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
It appears that no .lib files have been provided as part of the downloadable (.zip) binaries for Windows. This precludes users from statically linking the provided .dlls in their projects. The only work around I've found is to use LoadLibrary() or build the library from scratch. Perhaps more seasoned C++ developers could offer better advice.
Historically, .lib files were provided and made for easier integration.

# Environment
Visual Studio 14 (2015) x64
Visual Studio 15 (2017) x64

* libzmq version (commit hash if unreleased): 
* OS: Windows 10 Enterprise (17134.950)

# Minimal test code / Steps to reproduce the issue

1.  None. Could not find .lib to pass to the linker

# What's the actual result? (include assertion message & call stack if applicable)
NULL result. No .lib

# What's the expected result?
---

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: include all *.lib files

Fixes #3635

### CODE REVIEW

**Comment by sigiesec** [comment]
Can we also publish a new release with fixed artifacts on the website for download?

**Comment by somdoron** [comment]
Yes, it a bit manual. I will do next week. We have to delete existing files from bintray and then just tag (the name doesn't matter). I usually do it on my fork.

**Comment by somdoron** [comment]
@sigiesec artifacts republished.

**Comment by somdoron** [comment]
@sigiesec builds for mingw64 and cygwin are failing:

```
copy ..\..\lib\%Configuration%\libzmq*.lib .
The system cannot find the path specified.
```

https://ci.appveyor.com/project/zeromq/libzmq/builds/26985310

**Pull request merged**
