### PR TITLE
Fix for issue #1382

### PR DESCRIPTION
**Pull request by rikvdh**
This is the fix for issue #1382. Once it is merged I shall backport this to 4.1 and 4.0 repositories.

### CODE REVIEW

**Comment by hintjens** [comment]
Thanks for your fix, especially for adding a test case. Can you please squash these commits into a single commit? That's easier for others who want to work with this patch in the future. See git rebase. I can do the backport to 4.x stable. Also, see C4.1 for the style of commit messages ("Problem: ...").

**Comment by rikvdh** [comment]
Hi @hintjens 
I've squashed it all :)

**Comment by cachedout** [comment]
Hi @rikvdh and @hintjens 

This PR appears to have broken SaltStack's implementation of ZeroMQ whilst running on 4.0.6. :-/

Ref: https://github.com/saltstack/salt/issues/24630

We have determined that reverting the changes in `proxy.cpp` fixes the problem for us.

I do not know enough about ZMQ internals to begin to pretend that I know *why* this is so. However, I can certainly provide additional details as needed.

Since 4.0.6 has started to make its way into official distribution, such as Arch, this is a fairly critical issue for us. I'll continue to update this thread as we continue our investigation.

**Comment by rikvdh** [comment]
Hi @cachedout,

I don't know anything about SaltStack, but there already have been some fixes in proxy.cpp in the 4.x branch after the release. Can you please check whether these fix your problem? If they do, @hintjens can problably make a new release for 4.x.

Does this also happen on 4.1.x?

**Comment by cachedout** [comment]
Hi @rikvdh 

Thanks for your kind reply. Yes, it does look like the HEAD of the master branch on 4.x works correctly. Things also work correctly on the head of the master branch on 4.1.x.

We may just need a new git tag for a 4.x release that distros can pick up and package. That would solve the issue for us. Thanks again!

**Pull request merged**
