### PR TITLE
Problem: no tests for ZAP handler that has an invalid protocol

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: add tests

### CODE REVIEW

**Comment by sigiesec** [comment]
@bluca the CI jobs are now frequently failing due to test timeouts. The timeout seems to be fixed at 10 seconds. I don't know where to change that. test_security_curve now contains several test cases that each need to wait some time for remaining events. Since the CI nodes are terribly slow sometimes, it would not help to reduce these times. Do you see any other feasible option than increasing the test timeout?

**Comment by bluca** [comment]
I'm afraid it's testbed-specific and I really have no idea where the cloudapp stuff is.

Is it waiting for timeouts in connections?

**Comment by bluca** [comment]
@sigiesec actually it's probably a settings in cmake, that you might try and change: https://cmake.org/cmake/help/v3.0/command/set_tests_properties.html

**Comment by sigiesec** [comment]
Thanks for the cmake hint, will try that :)

**Comment by bluca** [comment]
@sigiesec I've seen another timeout on Windows:

https://ci.appveyor.com/project/zeromq/libzmq/build/job/2qo955y3n176fl75

bump to 30?

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/pull/2654

**Comment by sigiesec** [comment]
Hm... hope that helps... unless there is some case where no event is emitted at all, and the test waits forever... then the test or library must be fixed

**Comment by bluca** [comment]
Yeah if it still timeouts with 60 seconds it's definitely a hang

**Comment by sigiesec** [comment]
:( ok, will try to fix this. unfortunately, the tests behave quite differently on my local machine, so it is hard to reproduce for me. will add some more debug output

**Comment by bluca** [comment]
Yup it timed out again:

```
      Start 30: test_security_curve
30: Test command: C:\projects\build_libzmq\bin\Debug\test_security_curve.exe
30: Test timeout computed to be: 60
30/71 Test #30: test_security_curve ..............***Timeout  60.01 sec
```

Win32, debug, libsodium

https://ci.appveyor.com/project/zeromq/libzmq/build/build-1567/job/b0nei74paefqsomj

**Comment by sigiesec** [comment]
I added some more debug output, hope thats sheds some light onto the cause. 

https://ci.appveyor.com/project/sigiesec/libzmq/build/build-56 is running

But I fear I cannot continue before Monday.

**Comment by bluca** [comment]
no worries, it's not urgent

**Pull request merged**
