### PR TITLE
Problem: stream_engine_t instance may access its fields after it deleted itself

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: prevent access to data if the object was deleted

Fixes issue detected by clang static analyzer-: https://travis-ci.org/zeromq/libzmq/jobs/411364097#L2126

### CODE REVIEW

**Comment by bluca** [comment]
norm and pgm need to be updated too (see travis)

**Comment by sigiesec** [comment]
Should be fine now.

**Comment by bluca** [comment]
there's a test failing on OSX that wasn't failing before, could you please have a look?

**Comment by sigiesec** [comment]
@bluca I had a look, but I can't see a connection to the changes. The only change in behaviour is when ZAP is used, which is not the case with test_many_sockets.

**Comment by bluca** [comment]
Right, it was probably an overloaded OSX VM

**Pull request merged**
