### PR TITLE
default to not building tests if cmake version can't handle skipped tests

### PR DESCRIPTION
**Pull request by bill-torpey**
(see https://github.com/zeromq/libzmq/issues/4375)

### CODE REVIEW

**Comment by bluca** [comment]
please update the CI scripts to always run them

**Comment by bill-torpey** [comment]
> please update the CI scripts to always run them
 no idea what you mean -- didn't touch any ci scripts

**Comment by bluca** [comment]
There are CI scripts that run the tests, that now wouldn't, in builds/cmake/build.sh because of the new default - please change the scripts to explicitly enable the option, so that tests always run regardless of cmake version

**Comment by bill-torpey** [comment]
not at all familiar with CI framework, but at first glance it looks like those builds are (still) being done w/autotools?

**Comment by bill-torpey** [comment]
got it

**Pull request merged**
