### PR TITLE
Problem: pkg-config file cannot be used for static linking, missing dependencies in packaging

### PR DESCRIPTION
**Pull request by bluca**
Solution: add Requires.private which gets recursively expanded by applications to pkg-config

### CODE REVIEW

**Comment by EricLambrecht** [comment]
I have the same problem. I can't install any npm package that requires zeromq at the moment, which is kinda problematic.

**Comment by bluca** [comment]
Which dependency is missing?

**Comment by EricLambrecht** [comment]
@bluca we have an internal package in the company that uses "zeromq" and it can't be installed, because during installation (via npm/yarn), the build process fails because of this.

**Comment by bluca** [comment]
Again, which dependency is missing?

**Comment by EricLambrecht** [comment]
```
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/Transcend/***/***/***/node_modules/zeromq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/eric/.node-gyp/11.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/eric/.node-gyp/11.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/eric/.node-gyp/11.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/Transcend/***/***/***/node_modules/zeromq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:394:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
         ^
../../nan/nan.h:959:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../binding.cc:402:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
         ^
../../nan/nan.h:959:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../binding.cc:453:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
         ^
../../nan/nan.h:959:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../binding.cc:468:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
         ^
../../nan/nan.h:959:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../binding.cc:809:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
         ^
../../nan/nan.h:959:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../binding.cc:888:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
         ^
../../nan/nan.h:959:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
6 warnings generated.
  SOLINK_MODULE(target) Release/zmq.node
clang: error: no such file or directory: './Release/../../zmq/lib/libzmq.a'
make: *** [Release/zmq.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Transcend/***/***/***/node_modules/zeromq
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by bluca** [comment]
Autotools dependencies are missing on your system - specifically aclocal, which on Linux is usually installed via automake

**Comment by EricLambrecht** [comment]
@bluca  But I have aclocal-1.16 according to `aclocal --version`.

I could also pin the error down a little bit more. I don't get the error when I install it globally. It only happens when I try to install zeromq locally! The Warning regarding aclocal doesn't appear when I install it globally, too.

**Comment by bluca** [comment]
As you can see from the log, for whatever reason it's looking for aclocal-1.14, not 1.16. Note that this has nothing to do with libzmq at all, it's purely and exclusively an issue with the autotools setup on the machine you are running this from.

**Comment by EricLambrecht** [comment]
Okay just for documentation purposes. It seemed to be related to my external hard drive (or rather the path). When I created the project on my internal SSD, the problem was gone!

**Pull request merged**
