### PR TITLE
Problem: MAINTAINERS file has no purpose anymore

### PR DESCRIPTION
**Pull request by hitstergtd**
**Solution:**
Remove until such time that a new and appropriate file can replace it should it be deemed necessary.

### CODE REVIEW

**Comment by bluca** [comment]
You need to remove it from the list in Makefile.am too, otherwise the build breaks

**Comment by hitstergtd** [comment]
Ouch. The 4th wasn't with me @bluca. Let me fix it.

**Comment by hitstergtd** [comment]
Done.

**Comment by hitstergtd** [comment]
Thanks!

**Pull request merged**
