### PR TITLE
Add CMake Build Output Options

### PR DESCRIPTION
**Pull request by RPGillespie6**
See #2535 

Add two new options to CMakeLists.txt:

`BUILD_SHARED` - Whether or not to build the shared object (Default: ON)
`BUILD_STATIC` - Whether or not to build the static archive (Default: ON)

### CODE REVIEW

**Comment by bluca** [comment]
@RPGillespie6 could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by RPGillespie6** [comment]
Sure, who do I send the email to? Can I just state right here that I grant permission to use this PR under new license terms?

**Comment by bluca** [comment]
Yes, you can just state it here and I'll add it to the repository. Thank you!

**Comment by RPGillespie6** [comment]
I hereby grant permission to re-license the contents of this PR to any other software license including, but not limited to MPLV2.

**Comment by bluca** [comment]
Thank you, pushed via https://github.com/zeromq/libzmq/pull/3672

**Pull request merged**
