### PR TITLE
Adds NORM support to cmake

### PR DESCRIPTION
**Pull request by mjvk**
NORM was not yet supported in cmake. This adds that support.

### CODE REVIEW

**Comment by bluca** [comment]
You need also to add a cmakedefine to https://github.com/zeromq/libzmq/blob/master/builds/cmake/platform.hpp.in

**Comment by mjvk** [comment]
Will do! Could you explain to me why? The add_definition already outs it everywhere right?

**Comment by bluca** [comment]
I'm not sure, all other defines are there too

**Comment by mjvk** [comment]
I think it helps when recompiling. A define passed impacts all code. On in platform.hpp only the parts that include platform.hpp.

**Pull request merged**
