### PR TITLE
Problem: some test cases may still fail because of EPIPE/ECONNABORT/ECONNRESET

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: uniformly handle these error conditions in all test cases

### CODE REVIEW

**Comment by bluca** [comment]
I assume they were used for debugs, so should the fprintfs be dropped?

**Comment by bluca** [comment]
From the diff there seems to be only debug printfs? Or am I missing something?

**Comment by sigiesec** [comment]
The behavioural change is that all calls to get_monitor_event are replaced by get_monitor_event_with_timeout, which handles EPIPE/... 

I don't think the fprintf's should be dropped. They allow to see which test case was executed when an assertion fails. Using a test framework would remove the need for such boilerplate code.

**Comment by bluca** [comment]
ok, thanks, merged

**Pull request merged**
