### PR TITLE
Problem: Not all GCOV extensions in .gitignore

### PR DESCRIPTION
**Pull request by hitstergtd**
Solution:
Fix it.

### CODE REVIEW

**Comment by hitstergtd** [comment]
Thanks!

**Comment by hitstergtd** [comment]
How is it that Coveralls gets all excited about non source code commits?

**Comment by bluca** [comment]
It's very pedantic! :-)
Not sure if it can be fixed, couldn't see any settings. It will run on any build since it's on the CI, and just report what it finds.

I already tried to set the threshold for reporting but that only affects the test failing/passing, since there's obviously some rounding errors that make it report changes where there are actually none.

**Comment by hitstergtd** [comment]
Clearly. Thanks for the explanation. I am sure you were wondering if I had better PRs to spend time on instead of worrying about Coveralls' rounding errors and configurative inadequacies. :-)

**Pull request merged**
