### PR TITLE
Commit: Issue #2348

### PR DESCRIPTION
**Pull request by reza-ebrahimi**
Commit for Issue #2348
Problem: In zmq::socket_base_t::send method with or without ZMQ_ROUTER_MANDATORY option set

### CODE REVIEW

**Comment by bluca** [comment]
This breaks the test_router_mandatory_hwm pretty much everywhere, could you please have a look?

https://travis-ci.org/zeromq/libzmq/builds/204913151

Also please rebase and squash the fixup commits in the first one

**Comment by reza-ebrahimi** [comment]
@bluca I'll check it.

**Comment by hoditohod** [comment]
This breaks MANDATORY router behavior when HWM is reached: socket send should block or signal EAGAIN when ZMQ_DONTWAIT is used.

I think the tests updated in this commit were correct, and they were in sync with documentation.

**Comment by bluca** [comment]
Yes I agree, changing this would be an API breakage, and not sure we want it - EAGAIN is the right error when the pipe is full.
I think a change in check_write would be needed to differentiate between a failure because the pipe is gone or full, as it was mentioned on the mailing list a few days ago.
@somdoron any suggestions?

**Comment by somdoron** [comment]
I think the fix I made for NetMQ didnt change the api and fix the issue. Also I didnt change socket_base. I think we can apply the exact same change here

**Comment by somdoron** [comment]
https://github.com/zeromq/netmq/commit/30095a72ae3a9cfe8695f8010a94ff23be9fab7e

With this change, only if pipe is not active (during termination) host unreachable will be returned instead of eagain. Which doesnt break the api

**Comment by reza-ebrahimi** [comment]
I suggest we should check both pipe full or pipe closing state in the method and return proper error code, this will not break API, only documentation should be updated.


	if (it != outpipes.end()) {
		current_out = it->second.pipe;

		// check wheter pipe is full or not
		if (!current_out->check_hwm()) {
			it->second.active = false;
			current_out = NULL;
			if (mandatory)
				errno = EAGAIN;
		}
		// check wheter pipe is closed or not
		else if (!current_out->check_write()) {
			it->second.active = false;
			current_out = NULL;
			if (mandatory)
				errno = EHOSTUNREACH;
		}

		if (mandatory) {
			more_out = false;
			return -1;
		}
	}
	else if (mandatory) {
		more_out = false;
		errno = EHOSTUNREACH;
		return -1;
	}

**Comment by somdoron** [comment]
Looks good, one comment, not really critical.
Merging this one, can you also port the test from netmq in a new PR?

**Comment by reza-ebrahimi** [comment]
@somdoron Thanks, I'll be create netmq test, but I have a question,

This part of code is check when sending first frame of message as peer identity, so for main part of message this part is not reached and always returns with size of the written message and completely seems to be a legal operation whenever the peer is dead and pipe is not active and maybe destroyed?

**Comment by bluca** [comment]
@reza-ebrahimi @somdoron shouldn't the changes to the test be reverted? They are now failing

**Comment by reza-ebrahimi** [comment]
@bluca which test do you mean?

**Comment by bluca** [comment]
tests/test_router_mandatory_hwm.cpp

**Comment by bluca** [comment]
it's fine, I can send a PR to revert the changes to the test

**Comment by reza-ebrahimi** [comment]
@bluca Yes, I've checked test, it should reverted back to EAGAIN (retrying) state.

**Comment by reza-ebrahimi** [comment]
I'm just ask my question again,

This part of code is check when sending first frame of message as peer identity, so for second part of message, this part is not reached and always returns with size of written message and completely seems to be a legal operation whenever the peer is dead and pipe is not active and maybe destroyed?

First Frame --> send() // returns -1 , Wow! seems to be peer is dead (with ZMQ_ROUTER_MANDATORY)!
Second Frame --> send() // returns exactly message size! where message is sent??!

I think this check might be applied for second part of message too and both calls should return -1.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/pull/2353

**Comment by somdoron** [comment]
@reza-ebrahimi I think there is issue with the fix. Because now we might not call check_write (actually most of the time), important piece of code which mark the pipe as in active is not going to run. Actually with this fix, the pipe will never overcome the full state and will block forever. I think it even be easy to produce this issue.

I suggest to first call check_write, and inside to if block to call check_hwm.

**Comment by somdoron** [comment]
the process_active_write which suppose to make the pipe writeable again will not do so:

https://github.com/zeromq/libzmq/blob/master/src/pipe.cpp#L266

**Comment by reza-ebrahimi** [comment]
@somdoron I'm faced with that too, so I think this a wrong code inside check_write, so by its name check_write is a method that checks pipe is writable or not, so this is a bad code to set any state inside that,

```
bool zmq::pipe_t::check_write ()
{
    if (unlikely (!out_active || state != active))
        return false;

    bool full = !check_hwm();

    if (unlikely (full)) {
        out_active = false;
        return false;
    }

    return true;
}
```

I'm understand that piece of code inside ` if (unlikely (full)) {` was not calling moste of the time, I'm thinking about the solution.

**Comment by reza-ebrahimi** [comment]
@somdoron I have fixed the problem with a new method in pipe_t class, can I commit from this PR or create another one?

**Comment by somdoron** [comment]
New one...

**Comment by somdoron** [comment]
New one...

**Comment by reza-ebrahimi** [comment]
@somdoron PR issued. #2355

**Comment by reza-ebrahimi** [comment]
I think line 219 in write method is redundant, pipe_t class exposed checking methods public, so user should be applied checks before calling write method, in many places it called twice.

**Pull request merged**
