### PR TITLE
remove old fashion goto syntax and place ZMQ_DELETE macro for heap object deletion (ticket #1524)

### PR DESCRIPTION
**Pull request by reza-ebrahimi**
remove old fashion goto syntax and replace it with regular internally class method

### CODE REVIEW

**Comment by kevinkreiser** [comment]
not sure on the style guidelines but looks like some tabs got in there. just fyi

**Comment by jemc** [comment]
Let me just say I'm against this change - I think the `goto` style for errors is not "old fashioned", and actually has some nice benefits for reducing issues that arise in situations like when people need to refactor this code later, and forget to update one branch.

**Comment by c-rack** [comment]
I agree with @jemc. Pull requests should, by [definition](http://rfc.zeromq.org/spec:22) (excerpt):
1. A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.
2. A patch MUST adhere to the code style guidelines of the project if these are defined.

So from my point of view, this PR does not meet this criteria:
1. What is the problem to be solved? The only answer (which should be given by @reza-ebrahimi) I can imagine is to avoid `goto` completely. If that is the problem, than this PR is incomplete, since there are still a lot of other `goto` statements left in the project. Thus, it's not an accurate answer to the problem (if that is the problem to be solved), because this PR does not remove all `goto`s.
2. Common sense and coding style seems to be to have exactly _one_ exit point per function, which is achieved by using `goto`. Changing this coding style should be discussed in an issue rather than a PR.
3. This PR contains again tabs and not spaces, which is also against coding style guidelines. I already mentioned this in https://github.com/zeromq/libzmq/pull/1520.

@reza-ebrahimi, could you please open an issue which describes the problem you want to solve instead? Meanwhile, I would like to close this PR for the reasons I mentioned above.

@reza-ebrahimi It would be great if you could use git branches for your pull requests, because every pushed commit to your master branch is automatically added to your pull requests :-)

**Comment by reza-ebrahimi** [comment]
hmm, Ok, I would like to say you my plan in ZeroMQ contribution...
I want to improve ZeroMQ to meet the MISRA standard and HIC++ guidelines, these are standards that used in critical systems such as Aerospace or Oil & Gas industry applications, if this is not enough, we can argue about that,

so about the goto statement, you are right, this is my first step to remove it completely from project, this may not solve any problems but code goes to be clean and ..., so this is part of my effort to achieve mentioned standards...
and about my pull requests, that's ok, but before that review my next commit...

**Comment by reza-ebrahimi** [comment]
and about the tabs..., I'll fix all of the incorrect spaces in code.

**Comment by c-rack** [comment]
@reza-ebrahimi OK, not meeting the MISRA standard and HIC++ guidelines (have not heart about both before, links would be great) is a good problem description. Nevertheless, I would suggest to open a regular issue with that problem statement and provide a PR (using a branch) that solves this problem (completely). I cannot see why it should not be merged then.

By the way, thanks for contributing! :+1:

**Comment by reza-ebrahimi** [comment]
@c-rack Ok, but I can't understand, for every commit to master branch (main repo) I should open an issue?

**Comment by c-rack** [comment]
@reza-ebrahimi It is not necessary (but recommended) to open an issue for every change to the source. But it is good practise to open an issue which describes your problem, then create a branch that contains the solution for your problem and then submit a PR as the solution to your problem. If the problem you want to solve is small, it is OK to just send a simple PR (from a branch).

See also:
http://rfc.zeromq.org/spec:22
https://www.youtube.com/watch?v=xFVDNTXIC_Y

**Comment by hintjens** [comment]
It's good to be explicit about the problem you're addressing so that people
don't need to guess. Not meeting industry standards in the codebase is a
valid problem. Let's merge first, clarify second. Makes the conversation
smoother ...

**Comment by hintjens** [comment]
Also, I counsel against using branches, its extra work with little benefit.
Just make sure each PR states the problem clearly. Then then can be
pipelined... Since we aim to always merge anyhow.

**Comment by c-rack** [comment]
@hintjens Thanks for feedback. Let me reopen this PR then.

**Comment by reza-ebrahimi** [comment]
@hintjens Thanks for your hints, all of my efforts focused on clean API and meet industry standards.

**Comment by reza-ebrahimi** [comment]
@c-rack Thanks for reopening this PR, so I merged my new commits with this PR, by merging this commit, issue with ticket #1524 should be closed.

**Comment by bluca** [comment]
@reza-ebrahimi - according to the HIC++ v4.0 standard, using goto statements to jump to a common exit and cleanup point is compliant:

```
bool f3 (int (&array)[10][10])
{
for (int j1 = 0; j1 < 10; ++j1)
{
for (int j2 = 0; j2 < 10; ++j2)
{
if (array[j1][j2] == 0)
{
goto finished;
}
   
// ...
                     
}
}
                 
finished:           // @@+ Compliant +@@
return true;
}
```

http://www.codingstandard.com/rule/6-3-1-ensure-that-the-labels-for-a-jump-statement-or-a-switch-condition-appear-later-in-the-same-or-an-enclosing-block/

The Misra standard does not seem accessible without an account unfortunately, or at least I cannot find it on their website.

**Comment by reza-ebrahimi** [comment]
@bluca Yes, Both HIC++ and MISRA complains with goto statement, in MISRA with some restrictions:

MISRA C++: 2008 - Rule 6-6-1 (Rationale): 
Unconstrained use of goto can lead to programs that are extremely difficult to comprehend, analyse and, for C++, can also lead to the program exhibiting unspecified behaviour.

Since MISRA-C is aimed towards critical systems, MISRA-C:2004 has the approach to ban as many of these unconditional branch features as possible. Therefore, goto, continue and multiple returns were banned. break was only allowed if there was a single break inside the same loop.

so in my opinion the consensus of the world's programming community has roughly ended up something like goto, and our goal to modern C++ in ZeroMQ lead codebase to free from goto statements,

Yes The MISRA standard in not freely available, I have 2008 version, please give me your email address, I'll send it for you.

**Comment by bluca** [comment]
@reza-ebrahimi - But as far as I can understand, both HIC++ and MISRA allow for goto if used reasonably. Here, as far as I can see, it is used in a perfectly reasonable way, that is to have a common cleanup and exit point, which happens to be one of the examples that the HIC++ standard explicitly marks as accepted.

Also, I respectfully disagree with the assertion that there is a consensus in the world's programming community :-) In case you are interested, you can read the opinion of many Linux kernel developers in this thread [1], who _strongly_ feel the opposite.

Finally, there was recently a paper [2] that outlines some empirical research, and shows that there's no actual proof that goto statements are inherently bad and cause bugs.

All rigorously IMHO of course :-)

[1] http://koblents.com/Ches/Links/Month-Mar-2013/20-Using-Goto-in-Linux-Kernel-Code/
[2] https://peerj.com/preprints/826v1.pdf

**Pull request closed without merging**
