### PR TITLE
Problems: ZAP can be set up incorrectly, CURVE and GSSAPI can be used only with ZAP

### LINKED ISSUE #2594: Problem: CurveZMQ connection fails without ZAP
In commit a0ccdc866efbac5889d8872c7f27c53e9c0a7c5b from #2482 the logic of `curve_server.cpp` was changed so that `zmq::curve_server_t::process_initiate` returns -1 if `zap_connect` fails.  Previously, this was allowed and the ZAP logic was only processed if that returned 0.  Was this deliberate?  Is ZAP mandatory now?

### PR DESCRIPTION
**Pull request by bluca**
Solutions: see commits

Fixes #2594

### CODE REVIEW

**Comment by bluca** [comment]
@evoskuil please let me know if this looks good to you - thanks!

**Comment by bluca** [comment]
Ping :-)

**Comment by bjovke** [comment]
@bluca I can't help you here, I'm not familiar how this code works...

**Comment by evoskuil** [comment]
Thanks for the ping. I'm traveling for the next couple weeks and I can't give a very good review of this with just my iphone. The principle is sound but just looking it over in the browser it is hard to say for sure.

**Comment by bluca** [comment]
Thanks. Then I would recommend to go ahead with the changes to unblock folks using curve, and then we can revisit and revise if necessary.

**Pull request merged**
