### PR TITLE
Problems: build broken on centos6/ubuntu12, missing licenses and wrong copyright dates

### PR DESCRIPTION
**Pull request by bluca**
Solutions: fix them

### CODE REVIEW

**Comment by bluca** [comment]
@somdoron where did the sha1 files come from? We should add a version.txt file with a reference

**Comment by somdoron** [comment]
czmq...

**Comment by bluca** [comment]
lol! I'll see if I can find the origin from there

**Comment by somdoron** [comment]
We can replace with any implementation... @sigiesec suggested one

**Pull request merged**
