### PR TITLE
Problem: build fails due to undefined INT_MAX

### LINKED ISSUE #1720: Build failing on CI, on Linux
Currently, libzmq CI build is [failing](https://travis-ci.org/zeromq/libzmq/jobs/103594213).

I'm also getting the same error in czmq-ffi-gen: [here](https://travis-ci.org/paddor/czmq-ffi-gen/jobs/103648750).

```
[...]
  CXX    src/src_libzmq_la-vmci.lo
  CXX    src/src_libzmq_la-vmci_address.lo
  CXX    src/src_libzmq_la-vmci_connecter.lo
  CXX    src/src_libzmq_la-vmci_listener.lo
  CXX    src/src_libzmq_la-xpub.lo
  CXX    src/src_libzmq_la-xsub.lo
  CXX    src/src_libzmq_la-zmq.lo
src/zmq.cpp: In function ‘int s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int)’:
src/zmq.cpp:354:24: error: ‘INT_MAX’ was not declared in this scope
src/zmq.cpp: In function ‘int s_recvmsg(zmq::socket_base_t*, zmq_msg_t*, int)’:
src/zmq.cpp:466:24: error: ‘INT_MAX’ was not declared in this scope
src/zmq.cpp:467:1: error: control reaches end of non-void function [-Werror=return-type]
src/zmq.cpp: In function ‘int s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int)’:
src/zmq.cpp:355:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
make[1]: *** [src/src_libzmq_la-zmq.lo] Error 1
make[1]: Leaving directory `/home/travis/src/libzmq'
make: *** [all-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by c-rack**
Solution: include climits

Fixes #1720

### CODE REVIEW

**Comment by paddor** [comment]
Thanks. :) :+1:

**Comment by paddor** [comment]
Looks like `<cstdint>` is also missing.

**Comment by c-rack** [comment]
Could you please point me to the line with the error? In my fork, the test is passing:
https://travis-ci.org/c-rack/libzmq/builds/103659297

**Comment by paddor** [comment]
https://travis-ci.org/zeromq/libzmq/jobs/103662423#L1157

**Comment by c-rack** [comment]
Thanks. I forgot to rebase with master. Just updated the PR, hope it will pass now.

**Comment by c-rack** [comment]
So it still fails with `stdint.h` included. So I removed the `printf()` entirely. Next run.

**Comment by paddor** [comment]
Strange... I wonder why...

**Comment by c-rack** [comment]
Travis build has passed, finally :-)

**Pull request merged**
