### PR TITLE
Problem: msvc builds are misconfigured.

### PR DESCRIPTION
**Pull request by evoskuil**
See https://github.com/zeromq/libzmq/issues/1985

### CODE REVIEW

**Comment by evoskuil** [comment]
I can't tell because of the bogus Travis failures on the last run, or the one stress test failure on the previous run, whether the build actually succeeded or not - but it seems that it has.

**Comment by bluca** [comment]
Kicked the osx one, all good: https://travis-ci.org/zeromq/libzmq

**Comment by hitstergtd** [comment]
@evoskuil, this is really good, thanks! It might be an idea to remove the vs2008 msvc build as discussed, before shipping version v4.2. Or do you want me to send the PR?

**Comment by sunkin351** [comment]
It would be a good idea to consult the community before you stop support for vs2008.

**Comment by rgbkrk** [comment]
:smile:

**Comment by evoskuil** [comment]
Thanks @bluca.

@hitstergtd wrt 2008 it would be nice to get it out, but I agree with @sunkin351 that it would be a good idea to poll the community first.

**Pull request merged**
