### PR TITLE
Fix typos similar to #1894

### PR DESCRIPTION
**Pull request by hitstergtd**
Similar to pull request #1894

### CODE REVIEW

**Comment by c-rack** [comment]
@hitstergtd Thanks for the typo fixes!

If you look at our commit history, you will find that we use a problem/solution pattern for our commits.
It would be great if you could follow this style for your upcoming pull requests as well ;-)
I'd also recommend to learn more about our [C4.1 process](http://rfc.zeromq.org/spec:22).

**Comment by hitstergtd** [comment]
@c-rack, no problem. Apologies for not following process.

In terms of the problem/solution pattern, are you referring to the format of the Pull Request message?

**Comment by hitstergtd** [comment]
OK, I think I understand now. I will follow the format PH used in #1884, henceforth, for future Pulls.

**Comment by hitstergtd** [comment]
@c-rack Thanks for the merges!

**Pull request merged**
