### PR TITLE
Problem: autoconf-archive m4 macros out of date

### PR DESCRIPTION
**Pull request by hitstergtd**
**Solution:**
Update them from the latest archive located at:
git://git.savannah.gnu.org/autoconf-archive.git

### CODE REVIEW

**Comment by hitstergtd** [comment]
Just to add, I have tested it with: `./configure --enable-code-coverage --enable-valgrind` and seems to be fine, did some other odd builds too.

**Comment by hitstergtd** [comment]
Clearly, I need to setup Travis for my fork. :(

**Comment by bluca** [comment]
Makefile.am, configure.ac and builds/valgrind/ci_build.sh needs to be updated, as the API of the valgrind m4 has changed a little:

```
@VALGRIND_CHECK_RULES@
VALGRIND_FLAGS = --trace-children=yes
VALGRIND_memcheck_FLAGS = --leak-check=full
```

```
AX_VALGRIND_DFLT([sgcheck], [off])
AX_VALGRIND_DFLT([helgrind], [off])
AX_VALGRIND_DFLT([drd], [off])
AX_VALGRIND_DFLT([memcheck], [on])
AX_VALGRIND_CHECK
```

`make VERBOSE=1 check-valgrind`

**Comment by somdoron** [comment]
@hitstergtd let us know when this is ready to be merged

**Comment by hitstergtd** [comment]
@bluca I tried that before I fell asleep eventually, but it doesn't seem to be doing the trick, for some reason the new valgrind macro has borked Makefile.am.

@somdoron Thanks, yes, minor issues I will fix them today.

**Comment by bluca** [comment]
Interesting, I'll have a look

**Comment by bluca** [comment]
@hitstergtd - the diffs I posted work just fine both locally and on Travis: https://travis-ci.org/bluca/libzmq/jobs/127212798

Are you sure you regenerated from autotools? (./autogen.sh, ./configure etc)?

**Comment by hitstergtd** [comment]
@bluca That's odd. I have applied the exact same thing locally and I get:

```
./autogen.sh && ./configure --enable-valgrind && make -j5 && make VERBOSE=1 check-valgrind-memcheck
...
make[1]: Leaving directory `/core/forks/autoconf-m4/libzmq'
make: *** No rule to make target `check-valgrind-memcheck'. Stop.
```

**Comment by bluca** [comment]
Well yes, that doesn't exist anymore. As per the last snippet in my previous reply, builds/valgrind/ci_build.sh should be changed to simply run make check-valgrind.

**Comment by hitstergtd** [comment]
@bluca I posted the wrong snippet. I had already changed it make check-valgrind, but still bails out. :(

**Comment by hitstergtd** [comment]
@bluca I have pushed your changes as well. Lets see what happens. For some reason my build box just does not like `make check-valgrind`.

**Comment by bluca** [comment]
Worked fine on Travis apparently. Have you tried autoreconf -f -i ?

**Comment by hitstergtd** [comment]
@bluca I just checked the build, Travis passes because ci_build exits with return code 0, but the actual makefile target is still not generated for the underlying valgrind tools.

**Comment by bluca** [comment]
Oh, you're right sorry, didn't double check. Let me have a look again. This is the error:

```
+make VERBOSE=1 check-valgrind
make[1]: Entering directory `/home/travis/build/zeromq/libzmq'
make[1]: *** No rule to make target `check-valgrind-memcheck'.
make[1]: Leaving directory `/home/travis/build/zeromq/libzmq'
make: [check-valgrind] Error 2 (ignored)
```

**Comment by bluca** [comment]
The m4 checks for various things before enabling the macros. I suspect some of those checks are failing with the version of Valgrind that is on Travis (and your machine), it's the only logical explanation I can think of that would cause it to work on my machine but not on others.

I'm running 3.11 on Debian Stable, while Travis has 3.10.1.

**Comment by bluca** [comment]
Is there anything interesting in your config.status and config.log ?

**Comment by hitstergtd** [comment]
I have got GNU Make 3.81, Autoconf 2.69 and Automake 1.14.1.

**Comment by hitstergtd** [comment]
OK. I have nailed it I think. I believe Travis has an outdated GNU Make. :(

**Comment by hitstergtd** [comment]
@bluca 
Never mind. For now, I am backing out the valgrind related changes. It would mean changing Travis, etc., and I don't quite see the value add since your patch to the macros did pretty much the same thing. I have expended my remaining energy on autotools. :(

**Comment by bluca** [comment]
That's ok, thanks for checking :-) I'll have a look again, I have VMs with the same environment as Travis somewhere

**Comment by hitstergtd** [comment]
Thanks @bluca. No problem. I have cringe moments debugging autotools issues. :)

**Comment by bluca** [comment]
That makes the 2 of us (or 2000) :-)

**Pull request merged**
