### PR TITLE
Add relicense agreement from Spotify AB

### PR DESCRIPTION
**Pull request by caipre**
Granted by myself on behalf of Spotify for @gimaker, and @danielnorberg, who were contacted internally.

### CODE REVIEW

**Comment by bluca** [comment]
Thank you!

**Comment by danielnorberg** [comment]
Thanks!

**Comment by confiq** [comment]
any enlighting what this means?

**Comment by bluca** [comment]
see https://github.com/zeromq/libzmq/blob/master/RELICENSE/README.md

**Pull request merged**
