### PR TITLE
Problem: no mixed FD and zmq socket zmq_poll test

### PR DESCRIPTION
**Pull request by bluca**
Solution: add one

### CODE REVIEW

**Comment by bluca** [comment]
@minrk - without the change of https://github.com/zeromq/libzmq/pull/2250 this test case fails, so hopefully it can help give some insight in what was going wrong

**Comment by minrk** [comment]
Thanks! I see what was wrong now, and #2250 is almost right. I think I can come up with a test that will fail with master, and open a PR with the fix.

**Comment by bluca** [comment]
Perfect, thanks!

**Comment by minrk** [comment]
#2257 should be the 'right' fix for #2250, though once I realized the typo that prompted #2250, it's a safety check against internal code in libzmq, not against user code. That makes it much less likely to happen, and can't be triggered by a test case.

**Pull request merged**
