### PR TITLE
sodium, not Sodium

### PR DESCRIPTION
**Pull request by Teebonne**
sodium, not Sodium

### CODE REVIEW

**Comment by Bartel-C8** [comment]
Related warning:

```
-- Checking for module 'libsodium'
--   Found libsodium, version 1.0.18
CMake Warning (dev) at /Users/runner/cmake/cmake-3.24.2-macos-universal/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (sodium)
  does not match the name of the calling package (Sodium).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  builds/cmake/Modules/FindSodium.cmake:42 (find_package_handle_standard_args)
  CMakeLists.txt:265 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found sodium: /usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib  
-- Using libsodium for CURVE security
```

**Comment by bluca** [comment]
Please add a relicense statement https://github.com/zeromq/libzmq/tree/master/RELICENSE

Also please use the "Problem: ... Solution: ..." format in the commit message

**Comment by Teebonne** [comment]
Problem: Warning: The package name passed to `find_package_handle_standard_args` (sodium) does not match the name of the calling package (Sodium).
Solution: Changing the name from Sodium to sodium in CmakeLists fixes the problem.

**Comment by Teebonne** [comment]
I've added a relicense statement. Thanks!

**Pull request merged**
