### PR TITLE
Migrated some more tests to unity and fixed some more code style issues

### PR DESCRIPTION
**Pull request by sigiesec**
See individual commits

### CODE REVIEW

**Comment by sigiesec** [comment]
On which build did you see this?

**Comment by bluca** [comment]
https://travis-ci.org/zeromq/libzmq/jobs/382255893

**Comment by sigiesec** [comment]
I will check this tomorrow.

**Comment by bluca** [comment]
I've kicked it and it worked, might have been a borken travis container, if it happens again we can look again

**Pull request merged**
