### PR TITLE
Problem: Spelling of identifier "interface" matched a macro definition in VS2015

### PR DESCRIPTION
**Pull request by sunkin351**
Solution: spelling correction to "Interface".

Affected files:
udp_address.hpp
udp_address.cpp

### CODE REVIEW

**Comment by jemc** [comment]
@sunkin351 Rather than using an inconsistent capitalization here, what about just choosing a different spelling, like `iface`?

**Comment by sunkin351** [comment]
You can do that it you like, my goal was just to make it functional.

**Comment by jemc** [comment]
#1742 resolves this same problem without using inconsistent capitalization.

**Comment by hintjens** [comment]
We have this problem all the time, and our usual solution is to use 'iface'.

**Pull request closed without merging**
