### PR TITLE
Problem: condition var methods not explicitly deleted.

### PR DESCRIPTION
**Pull request by evoskuil**

### CODE REVIEW

**Comment by bluca** [comment]
breaks some builds:

```
../src/condition_variable.hpp:322:59: error: defaulted and deleted functions only available with -std=c++0x or -std=gnu++0x [-Werror]
../src/condition_variable.hpp:323:76: error: defaulted and deleted functions only available with -std=c++0x or -std=gnu++0x [-Werror]
```

**Comment by evoskuil** [comment]
Ugh, c++11 only.

**Comment by bluca** [comment]
It's fine to have IFDEFS for that, if you want - other places in the code already do

**Comment by evoskuil** [comment]
Prob not worth it.

**Pull request closed without merging**
