### PR TITLE
Problem: test_stream_exceeds_buffer cannot be ran in parallel

### PR DESCRIPTION
**Pull request by bluca**
Solution: bind to wildcard and let the OS pick a free port instead
of using an hard-coded 12345 TCP port

### CODE REVIEW

**Comment by ricnewton** [comment]
Merged build triggered.

**Comment by ricnewton** [comment]
Merged build started.

**Comment by ricnewton** [comment]
Merged build finished.

**Comment by jimklimov** [comment]
LGTM

FYI, the failure on @ricnewton was a weird one, in Java (not the tested code): 
````
100% tests passed, 0 tests failed out of 75

Total Test time (real) = 112.73 sec
[locks-and-latches] Releasing all the locks
[locks-and-latches] All the locks released
[WARNINGS] Parsing warnings in console log with parser MSBuild
[WARNINGS] Computing warning deltas based on reference build #1907
[WARNINGS] Ignore new warnings since this is the first valid build
[WARNINGS] Plug-in Result: Success - no threshold has been exceeded
Setting commit status on GitHub for https://github.com/zeromq/libzmq/commit/f8fe71fbdb9f0cac6d78e2ef54981befcd1cfc54
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
org.codehaus.jackson.JsonParseException: Numeric value (4308659692) out of range of int
 at [Source: java.io.StringReader@16aba8c; line: 1, column: 118]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserBase.convertNumberToInt(JsonParserBase.java:829)
	at org.codehaus.jackson.impl.JsonParserBase.getIntValue(JsonParserBase.java:625)
	at org.codehaus.jackson.map.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:303)
````

Travis failed one task in OSX with a sysadmin error as well:
````
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
The command "if [ $TRAVIS_OS_NAME == "osx" -a $CURVE == "libsodium" ] ; then brew install libsodium ; fi" failed and exited with 1 during .
````

**Comment by bluca** [comment]
Thanks - yes the Jenkins -> Github integration broke a couple of weeks ago.

**Pull request merged**
