### PR TITLE
problem: no way to send raw udp messages with zeromq.

### PR DESCRIPTION
**Pull request by somdoron**
continue @Bitiquinho work on #1986

### CODE REVIEW

**Comment by bluca** [comment]
tests/test_dgram is autogenerated script by autoconf, it should not be checked in git, but rather added to .gitignore. Could you please fix and squash it up?

**Comment by somdoron** [comment]
@bluca that should have happened...

fixed.

**Comment by somdoron** [comment]
it seems build is failing on windows... I'm working on that

**Comment by bluca** [comment]
Thanks! Let me know when you are done and I'll merge.

**Comment by somdoron** [comment]
@bluca can be merged

**Comment by bluca** [comment]
Cool. Awesome stuff!
@Bitiquinho - feel free to send another PR and add yourself to the AUTHORS file.

**Comment by bluca** [comment]
@somdoron @Bitiquinho - Valgrind is reporting accessing of uninitialised memory in zmq::udp_engine_t::resolve_raw_address:

https://travis-ci.org/zeromq/libzmq/jobs/130532559

Do you have time to have a quick look?

**Comment by hitstergtd** [comment]
And do we need to add test_dram to .gitignore?

**Comment by hitstergtd** [comment]
Never mind it's already there!

**Comment by somdoron** [comment]
@bluca #1996

**Comment by Bitiquinho** [comment]
@somdoron 
Thanks a lot for helping me out on that one

**Comment by Bitiquinho** [comment]
@bluca 
Could I add myself ?
How should I name/justify the PR ?

**Comment by bluca** [comment]
@Bitiquinho - yes, it is actually part of the C4 dev process we follow. It's especially important since you added new files and you own the copyright to them. Simply do a single commit with message

"Problem: my name is not in the AUTHORS file

Solution: add it"

And I'll merge it :-)

**Pull request merged**
