### PR TITLE
Partial Windows XP support

### PR DESCRIPTION
**Pull request by diorcety**
PR for bug #2612

### CODE REVIEW

**Comment by somdoron** [comment]
Wont this make new socket types unsusable on windows?

**Comment by bluca** [comment]
Yes, all new sockets test cases are failing

**Comment by somdoron** [comment]
I think it is better to leave the default as windows vista. If someone one to compile for windows xp they can set the WINNT flag.

**Comment by diorcety** [comment]
I will try to resolve that. I'am a bit busy now

**Comment by diorcety** [comment]
Every thing seems good now. MSVC doesn't set correctly _cplusplus. Using _MSC_VER we can enable or not the conditional_variable usage or not.

**Comment by bjovke** [comment]
@diorcety I'm not sure this is OK. It changes default Windows version from Vista to XP for the whole library, breaking the compatibility.
The offending part of the code is this one:
```
#undef _WIN32_WINNT
#define _WIN32_WINNT 0x0600
```
In my opinion, only this should be changed. If user has defined `_WIN32_WINNT` and it is XP or higher (Windows 10 in case of UWP), then it should not be undefined and set to different value. This means that user must explicitly enable XP support while default behavior should be Vista and Windows 10 in case of UWP.

**Comment by bjovke** [comment]
@diorcety Generally this PR is ok, [this](https://github.com/zeromq/libzmq/pull/2619/commits/fa0f3889fa18b8e8a65772bafb899e423b6c7e41#diff-e81114d231ae71d13f16d1b6970abb37R64) and [this](https://github.com/zeromq/libzmq/pull/2619/commits/fa0f3889fa18b8e8a65772bafb899e423b6c7e41#diff-7af18dafe332fc0e0aee2c444d29231eR43) are the only offending lines. It should be changed to `0x0600`.

**Comment by diorcety** [comment]
Done

**Comment by bluca** [comment]
@diorcety could you please send a new pull request or an email with a relicense statement? As explained in https://github.com/zeromq/libzmq/blob/master/.github/CONTRIBUTING.md and https://github.com/zeromq/libzmq/tree/master/RELICENSE we are trying to relicense libzmq under MPL-2. Thank you!

**Comment by diorcety** [comment]
@bluca Done with #3666

**Pull request merged**
