### PR TITLE
Problem: CI build android on ubuntu-latest failed

### LINKED ISSUE #4725: CI build android on ubuntu-latest failed
# Issue description
## Error logs:
ld.lld: error: non-exported symbol '__aeabi_ldivmod' in '/usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/libclang_rt.builtins-arm-android.a(aeabi_ldivmod.S.o)' is referenced by DSO 'src/.libs/libzmq.so'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:4155: perf/local_lat] Error 1
make[1]: Leaving directory '/home/runner/work/libzmq/libzmq/libzmq'
make: *** [Makefile:8442: install-recursive] Error 1
Error: Process completed with exit code 1.

More details: https://github.com/zeromq/libzmq/actions/runs/10338824667/job/28617425863

## Problem analysis:
The current project only supports android-ndk-r25, while ubuntu-latest provides android-ndk-r27 by default.

## Solution:
Fix the NDK version in the CI script to android-ndk-r25 before the project adapts to other NDK versions.

### PR DESCRIPTION
**Pull request by githejie**
Solution: Fixed the NDK version to android-ndk-r25 to avoid using unsupported NDK version on ubuntu-latest.

Fixes #4725

### CODE REVIEW

**Comment by stephan57160** [comment]
I think that this script is generated by ZProject.
Hence, your modification will be lost next time this project is re-generated.

I think I modified this variable initialization, to allow NDK configuration, as per development need.
Temporarily, this (or something similar) should help : 
```
export NDK_VERSION=android-ndk-r25c
export ANDROID_NDK_ROOT=<my_prefered_ndk_root>
./ci_build.sh
```
Given NDK will/should be downloaded automatically during the build, if not already available.
At least, this was the goal...

I add @benjdero, as he might have some other fix pending for another issue with NDK 25.

**Comment by stephan57160** [comment]
See this : 
https://github.com/zeromq/libzmq/tree/master/builds/android#android-ndk

**Comment by githejie** [comment]
Hi @stephan57160, thanks for your comment.

I previously specified the NDK version in `ci_build.sh` because I thought `ci_build.sh` was specifically for GitHub action, and users would use `build.sh` for local builds.

After considering your comment, I think it is more reasonable to use environment variables in `CI.yaml` to specify the NDK version.

**Comment by stephan57160** [comment]
> I previously specified the NDK version in `ci_build.sh` because I thought `ci_build.sh` was specifically for GitHub action, and users would use `build.sh` for local builds.

It was like this previously, yes.
But it was a nightmare to have ZYRE, CZMQ and LIBZMQ in sync regarding NDK versions.

**Comment by benjdero** [comment]
This seems to be the right solution 👍

**Pull request merged**
