### PR TITLE
problem: WS transport doesn't support mechanism

### PR DESCRIPTION
**Pull request by somdoron**
Solution: add support to mechanism

### CODE REVIEW

**Comment by bluca** [comment]
valgrind says:

```
==25566== Conditional jump or move depends on uninitialised value(s)
==25566==    at 0x4EE751C: zmq::ws_decoder_t::opcode_ready(unsigned char const*) (ws_decoder.cpp:68)
```

Can tmpbuf be initialized to 0 in the constructor to make it happy?

**Comment by somdoron** [comment]
@bluca fixed

**Comment by bluca** [comment]
@somdoron the test (before this PR) seem to get stuck every now and then:

[  310s] ./config/test-driver: line 107:  9187 Alarm clock             "$@" > $log_file 2>&1
[  310s] FAIL: tests/test_wss_transport

**Comment by somdoron** [comment]
:( I will check it

**Comment by somdoron** [comment]
@bluca I think it is fixed by #3703.

It also explains the valgrind warning.

**Pull request merged**
